Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2018-10, with the labels that each got.

#33 Add coverage report and status badge
  .travis.yml
  README.md
Labels: cncf-cla: yes, lgtm

#29 Add unit test for util package
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, size/M

#40 Rename
  .travis.yml
  Makefile
  README.md
  cmd/aws-ebs-csi-driver/main.go
  deploy/docker/Dockerfile
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/cloud/metadata_test.go
  pkg/cloud/mocks/mock_ec2.go
  pkg/cloud/mocks/mock_ec2metadata.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  tests/e2e/e2e_test.go
  tests/e2e/setup_test.go
  tests/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#43 Fix go import path for go module
  go.mod
Labels: approved, cncf-cla: yes, size/XS

#46 Disable build for go master branch
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#45 Update cloud provider interface to take in context
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/cloud/mocks/mock_ec2.go
  pkg/cloud/mocks/mock_ec2metadata.go
  pkg/driver/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#44 Add update-gomock script to generate mock files for testing
  hack/update-gomock
Labels: approved, cncf-cla: yes, lgtm, size/S

#47 Fix paths in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#34 Wait for volume status in e2e test
  tests/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/L

#49 Add full location for fedora-minimal image
  deploy/docker/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#53 Don't pick random AZ on volume creation
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/mocks/mock_ec2.go
Labels: approved, cncf-cla: yes, kind/bug, size/M

#56 Add README for CSI driver example
  deploy/kubernetes/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#51 Update manifests so driver is registered correctly
  deploy/kubernetes/v1.12+/attacher.yaml
  deploy/kubernetes/v1.12+/node.yaml
  deploy/kubernetes/v1.12+/provisioner.yaml
  deploy/kubernetes/v1.12+/sample_app/claim.yaml
  deploy/kubernetes/v1.12+/sample_app/pod.yaml
  deploy/kubernetes/v1.12+/sample_app/storageclass.yaml
  deploy/kubernetes/v1.12+/secret.yaml
  deploy/kubernetes/v1.[10,11]/attacher.yaml
  deploy/kubernetes/v1.[10,11]/node.yaml
  deploy/kubernetes/v1.[10,11]/provisioner.yaml
  deploy/kubernetes/v1.[10,11]/sample_app/claim.yaml
  deploy/kubernetes/v1.[10,11]/sample_app/pod.yaml
  deploy/kubernetes/v1.[10,11]/sample_app/storageclass.yaml
  deploy/kubernetes/v1.[10,11]/secret.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#57 Fix typo in README
  deploy/kubernetes/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#60 Update README
  deploy/kubernetes/README.md
Labels: approved, cncf-cla: yes, size/S

#58 Wait for attachment state after attach/detach
  Makefile
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  tests/e2e/e2e_test.go
  tests/e2e/setup_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#68 Remove hard-coded region in e2e test
  tests/e2e/setup_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#67 Implement support for storage class parameter - fsType
  pkg/cloud/cloud.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#61 Add missing capability and clusterrole permission to enable topology awareness scheduling
  deploy/kubernetes/v1.12+/node.yaml
  deploy/kubernetes/v1.12+/provisioner.yaml
  pkg/driver/identity.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#70 Update manifests
  deploy/kubernetes/v1.12+/attacher.yaml
  deploy/kubernetes/v1.12+/node.yaml
  deploy/kubernetes/v1.12+/provisioner.yaml
  deploy/kubernetes/v1.[10,11]/attacher.yaml
  deploy/kubernetes/v1.[10,11]/node.yaml
  deploy/kubernetes/v1.[10,11]/provisioner.yaml
Labels: approved, cncf-cla: yes, size/S

#71 Add more info in README
  README.md
  deploy/kubernetes/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#73 Implement support for storage class parameter - volume type
  pkg/cloud/cloud.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#69 Switch to Alpine 3.8 as base image
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#76 Update README for driver features
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#80 Add support for creating encrypted volume
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#81 Remove unit test and sanity test in favor of prow job
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#84 Update copyright years
  pkg/cloud/devicemanager/allocator.go
  pkg/cloud/devicemanager/allocator_test.go
Labels: approved, cncf-cla: yes, size/XS

#85 Refactor `GetDevice` method.
  pkg/cloud/devicemanager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M
