Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2018-12, with the labels that each got.

#133 Add example IAM policy
  docs/README.md
  docs/example-iam-policy.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#127 Remove unsupported MULTI_NODE_READER_ONLY volume capability
  pkg/driver/driver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#132 Resolve memory addresses in log messages
  pkg/driver/controller.go
  pkg/driver/identity.go
  pkg/driver/node.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#138 Partially revert PR #122 and add latest manifest files
  deploy/kubernetes/latest/attacher.yaml
  deploy/kubernetes/latest/node.yaml
  deploy/kubernetes/latest/provisioner.yaml
  deploy/kubernetes/latest/sample_app/claim.yaml
  deploy/kubernetes/latest/sample_app/pod.yaml
  deploy/kubernetes/latest/sample_app/storageclass.yaml
  deploy/kubernetes/latest/secret.yaml
  deploy/kubernetes/v1.12/attacher.yaml
  deploy/kubernetes/v1.12/node.yaml
  deploy/kubernetes/v1.12/provisioner.yaml
  deploy/kubernetes/v1.12/sample_app/claim.yaml
  deploy/kubernetes/v1.12/sample_app/pod.yaml
  deploy/kubernetes/v1.12/sample_app/storageclass.yaml
  deploy/kubernetes/v1.12/secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#136 Add version flag
  Makefile
  cmd/main.go
  pkg/driver/driver.go
  pkg/driver/identity.go
  pkg/driver/version.go
  pkg/driver/version_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#140 Bump vendored kubernetes to v1.12.3
  .travis.yml
  Dockerfile
  docs/README.md
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#135 Refactor the code
  cmd/main.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/fakes.go
  pkg/driver/node.go
  tests/integration/setup_test.go
  tests/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, size/M

#130 Add mountOptions support
  pkg/driver/node.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#147 Fix README
  docs/README.md
Labels: approved, cncf-cla: yes, size/M

#148 Fix Links in README
  docs/README.md
Labels: approved, cncf-cla: yes, size/XS

#154 Bump driver version to 0.2.0
  Makefile
  deploy/kubernetes/latest/attacher.yaml
  deploy/kubernetes/latest/node.yaml
  deploy/kubernetes/latest/provisioner.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, size/S

#156 Fix integration Test
  pkg/cloud/cloud.go
  tests/integration/integration_test.go
  tests/integration/setup_test.go
Labels: approved, cncf-cla: yes, size/XS

#153 Move test integration
  Makefile
  hack/test-integration.sh
  tests/integration/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#160 Fix klog flag init
  cmd/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
