Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2019-07, with the labels that each got.

#315 Remove snapshot from default manifest and make it configurable from helm
  aws-ebs-csi-driver/templates/manifest.yaml
  aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/manifest.yaml
  hack/run-e2e-test
  hack/utils/helm.sh
  hack/utils/tiller-rbac.yaml
Labels: approved, cncf-cla: yes, size/L

#321 Update README
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#322 Update manifest for Kubernetes 1.15
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
