Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2019-03, with the labels that each got.

#225 Add liveness probe
  deploy/kubernetes/controller.yaml
  deploy/kubernetes/node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#230 Minor change to rename field name for global mount path
  pkg/driver/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#232 Cleanup README and examples
  docs/README.md
  examples/kubernetes/pod-single-volume/README.md
  examples/kubernetes/pod-single-volume/specs/claim.yaml
  examples/kubernetes/pod-single-volume/specs/pod.yaml
  examples/kubernetes/pod-single-volume/specs/storageclass.yaml
  examples/kubernetes/snapshot/README.md
  examples/kubernetes/snapshot/specs/app/claim.yaml
  examples/kubernetes/snapshot/specs/app/pod.yaml
  examples/kubernetes/snapshot/specs/classes/snapshotclass.yaml
  examples/kubernetes/snapshot/specs/classes/storageclass.yaml
  examples/kubernetes/snapshot/specs/snapshot-restore/claim.yaml
  examples/kubernetes/snapshot/specs/snapshot-restore/pod.yaml
  examples/kubernetes/snapshot/specs/snapshot/snapshot.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#231 Implement device path discovery for NVMe support
  pkg/driver/node.go
  pkg/driver/node_test.go
  tests/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#236 Update image for runtime deployment
  docs/imgs/runtime-deployment.png
Labels: approved, cncf-cla: yes, size/XS

#235 New volume snapshot e2e tests
  go.mod
  go.sum
  hack/feature-gates.yaml
  tests/e2e/driver/driver.go
  tests/e2e/driver/ebs_csi_driver.go
  tests/e2e/dynamic_provisioning.go
  tests/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  tests/e2e/testsuites/specs.go
  tests/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#238 Add example for block volume
  examples/kubernetes/block-volume/README.md
  examples/kubernetes/block-volume/specs/pod.yaml
  examples/kubernetes/block-volume/specs/raw-claim.yaml
  examples/kubernetes/block-volume/specs/storageclass.yaml
  examples/kubernetes/pod-single-volume/README.md
Labels: approved, cncf-cla: yes, size/M

#239 Update driver README
  docs/README.md
  examples/kubernetes/snapshot/README.md
Labels: approved, cncf-cla: yes, size/L

#240 Update example folder name
  docs/README.md
  examples/kubernetes/dynamic-provisioning/README.md
  examples/kubernetes/dynamic-provisioning/specs/claim.yaml
  examples/kubernetes/dynamic-provisioning/specs/pod.yaml
  examples/kubernetes/dynamic-provisioning/specs/storageclass.yaml
Labels: approved, cncf-cla: yes, size/XS

#241 Update driver version
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#244 Update CHANGELOG for 0.3 release
  CHANGELOG-0.x.md
Labels: approved, cncf-cla: yes, size/S

#245 Update driver image tag to 0.3 for release
  deploy/kubernetes/controller.yaml
  deploy/kubernetes/node.yaml
Labels: approved, cncf-cla: yes, size/XS

#248 Post 0.3 documentation changes
  CHANGELOG-0.x.md
  deploy/kubernetes/controller.yaml
  deploy/kubernetes/node.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, size/S

#249 Add release script
  hack/release
Labels: approved, cncf-cla: yes, size/M

#247 Make secret optional
  deploy/kubernetes/controller.yaml
Labels: approved, cncf-cla: yes, size/XS

#254 Combine driver manifests
  deploy/kubernetes/manifest.yaml
  deploy/kubernetes/node.yaml
  docs/README.md
  hack/run-e2e-test
Labels: approved, cncf-cla: yes, size/L

#253 Add support for XFS filesystem
  Dockerfile
  docs/README.md
  examples/kubernetes/storageclass/README.md
  examples/kubernetes/storageclass/specs/example.yaml
  pkg/driver/node.go
Labels: approved, cncf-cla: yes, size/M

#258 Remove mount type for node publish
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, size/S
