Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2019-04, with the labels that each got.

#260 Update README for driver permission
  docs/README.md
Labels: approved, cncf-cla: yes, size/S

#257 Refactor driver to modularize node service and controller service
  pkg/cloud/cloud.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/fakes.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, size/L

#263 Upgrade CSI spec to 1.1.0
  go.mod
  go.sum
  pkg/driver/controller.go
  pkg/driver/node.go
Labels: approved, cncf-cla: yes, size/S

#266 Bump driver version
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#270 Update log verbosity and log message
  pkg/cloud/devicemanager/manager.go
  pkg/driver/controller.go
  pkg/driver/identity.go
  pkg/driver/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#267 Refactor integration test script
  Makefile
  hack/run-integration-test
Labels: approved, cncf-cla: yes, lgtm, size/M

#273 Increase log verbosity for probe call
  pkg/driver/identity.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#275 Update README
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#269 Refactor controller unit test with proper mock
  hack/update-gomock
  pkg/cloud/cloud_test.go
  pkg/cloud/metadata.go
  pkg/cloud/mocks/mock_ec2.go
  pkg/cloud/mocks/mock_ec2metadata.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/fakes.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/mocks/mock_metadata_service.go
  pkg/driver/node_test.go
  pkg/util/util.go
  tests/sanity/fake_cloud_provider.go
  tests/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#276 Fix e2e test when pod start times out
  tests/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
Labels: approved, cncf-cla: yes, size/XS

#277 Rename driver sa, clusterrole and clusterrole binding to be driver specific
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#274 Refactor device path allocator
  pkg/cloud/devicemanager/allocator.go
  pkg/cloud/devicemanager/allocator_test.go
  pkg/cloud/devicemanager/manager.go
  pkg/cloud/devicemanager/manager_test.go
Labels: approved, cncf-cla: yes, size/L

#281 Fix liveness probe memory leak
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#282 Fix liveness probe memory leak
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, size/XS
