Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2019-05, with the labels that each got.

#283 Make storageclass paramter case in-sensitive
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  tests/e2e/driver/ebs_csi_driver.go
  tests/e2e/dynamic_provisioning.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#293 Return correct error when restoring non-existent snapshot
  pkg/cloud/cloud.go
  pkg/driver/controller.go
Labels: cncf-cla: yes, lgtm, size/XS

#289 Add max number of volumes that can be attached to an instance
  pkg/cloud/metadata.go
  pkg/cloud/metadata_test.go
  pkg/driver/mocks/mock_metadata_service.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  tests/e2e/pre_provsioning.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#286 Implementing ListSnapshots
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/mocks/mock_cloud.go
  tests/sanity/fake_cloud_provider.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#288 Update sanity tests
  go.mod
  go.sum
  tests/sanity/fake_cloud_provider.go
  tests/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#298 Device allocator should not use reserved dev names.
  pkg/cloud/devicemanager/allocator.go
  pkg/cloud/devicemanager/allocator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#291 Update e2e test to run against 1.14.0
  deploy/kubernetes/manifest.yaml
  hack/run-e2e-test
Labels: approved, cncf-cla: yes, size/S

#301 Refactor node unit test to use Mounter interface
  hack/update-gomock
  pkg/driver/fakes.go
  pkg/driver/mocks/mock_mounter.go
  pkg/driver/mount.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, size/XXL

#302 Fix readme curl path for secret
  docs/README.md
Labels: approved, cncf-cla: yes, size/XS
