Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2019-09, with the labels that each got.

#360 Switch to use kustomize for manifest
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/csidriver.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/rbac.yaml
  deploy/kubernetes/manifest.yaml
  deploy/kubernetes/overlays/alpha/controller_add_resizer.yaml
  deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
  deploy/kubernetes/overlays/alpha/kustomization.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_resizer.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, size/XL

#359 Use new test framework for test orchestration
  Makefile
  go.mod
  go.sum
  tester/cmd/main.go
  tester/migration-test-config.yaml
  tester/multi-az-config.yaml
  tester/single-az-config.yaml
Labels: approved, cncf-cla: yes, size/L

#363 Update tester version
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#364 Update README for installation step
  docs/README.md
Labels: approved, cncf-cla: yes, size/XS

#367 Update README
  docs/README.md
Labels: approved, cncf-cla: yes, size/XS

#369 enable users to set ec2-endpoint for nonstandard regions
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#377 Add design doc
  docs/design.md
Labels: approved, cncf-cla: yes, size/L

#379 Add standard volume type
  docs/README.md
  go.sum
  pkg/cloud/cloud.go
  pkg/driver/controller_test.go
  tests/e2e/driver/ebs_csi_driver.go
Labels: approved, cncf-cla: yes, size/M

#380 Enable leader election
  aws-ebs-csi-driver/templates/manifest.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/rbac.yaml
  deploy/kubernetes/overlays/alpha/controller_add_resizer.yaml
  deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
Labels: approved, cncf-cla: yes, size/S
