Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2019-10, with the labels that each got.

#382 Update READEME
  docs/README.md
Labels: approved, cncf-cla: yes, size/XS

#383 Add github workflow to build and publish container image
  .github/workflows/container-image.yaml
Labels: approved, cncf-cla: yes, size/M

#385 Update README
  docs/README.md
Labels: approved, cncf-cla: yes, size/S

#386 Update aws sdk version to enable EKS IAM for SA
  deploy/kubernetes/base/rbac.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  go.mod
  go.sum
  pkg/cloud/cloud.go
Labels: approved, cncf-cla: yes, size/L

#390 Fix typo
  tests/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
Labels: approved, cncf-cla: yes, size/XS

#391 Update README
  Makefile
  docs/README.md
  go.sum
  hack/verify-golint
Labels: approved, cncf-cla: yes, size/S

#392 Update version string
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#353 Add a cmdline option to add extra volume tags
  cmd/main.go
  go.mod
  pkg/cloud/cloud.go
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/fakes.go
  pkg/driver/validation.go
  pkg/driver/validation_test.go
  tests/integration/setup_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL
