Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2019-12, with the labels that each got.

#424 Use main from e2e tester
  Makefile
  go.mod
  go.sum
  tester/cmd/main.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/M

#420 Added tolerations for node support
  aws-ebs-csi-driver/templates/manifest.yaml
  aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#430 Handle mount flags in NodeStageVolume
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#375 Return success if instance or volume are not found
  pkg/cloud/cloud.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M
