Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2019-08, with the labels that each got.

#325 Remove the deprecated connection-timeout flag for liveness probe
  Makefile
  aws-ebs-csi-driver/templates/manifest.yaml
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, size/XS

#328 Add node selector for linux node only
  aws-ebs-csi-driver/templates/manifest.yaml
  deploy/kubernetes/manifest.yaml
Labels: approved, cncf-cla: yes, size/XS

#329 Upgrade to golang 1.12
  .travis.yml
  Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#327 Update helm manifest for 1.15
  aws-ebs-csi-driver/templates/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#336 Add documentations for volume resizing
  docs/README.md
  examples/kubernetes/resizing/README.md
  examples/kubernetes/resizing/spec/example.yaml
Labels: approved, cncf-cla: yes, size/M

#340 Output junit to ARTIFACTS for testgrid
  hack/run-e2e-test
  tests/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#337 Running multi-az e2e test using Nitro instance
  Makefile
  hack/run-e2e-test
Labels: approved, cncf-cla: yes, size/XS

#344 Remove DISCLAIM
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#345 Update to use kubernetes 1.15 as dependency
  go.mod
  go.sum
  hack/update-gomod.sh
  tests/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#348 Update readme
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#349 Update copyright to 2019
  Dockerfile
  Makefile
  NOTICE
  cmd/main.go
  hack/release
  hack/run-e2e-test
  hack/run-integration-test
  hack/test-integration.sh
  hack/update-gofmt
  hack/update-gomock
  hack/update-gomod.sh
  hack/verify-all
  hack/verify-gofmt
  hack/verify-golint
  hack/verify-govet
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/devicemanager/allocator.go
  pkg/cloud/devicemanager/allocator_test.go
  pkg/cloud/devicemanager/manager.go
  pkg/cloud/devicemanager/manager_test.go
  pkg/cloud/metadata.go
  pkg/cloud/metadata_test.go
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/fakes.go
  pkg/driver/identity.go
  pkg/driver/internal/inflight.go
  pkg/driver/internal/inflight_test.go
  pkg/driver/mount.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/driver/version.go
  pkg/driver/version_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, size/M

#343 Update CHANGELOG for 0.4 release
  CHANGELOG-0.x.md
  docs/README.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/M

#354 Add docker ignore to ignore vendor dir
  .dockerignore
Labels: approved, cncf-cla: yes, size/XS

#355 Implement auto generating change log
  hack/release
Labels: approved, cncf-cla: yes, size/M

#358 Skip new k8s-specific test that needs SSH
  hack/run-e2e-test
Labels: approved, cncf-cla: yes, lgtm, size/XS
