Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2019-02, with the labels that each got.

#197 Refactor util package and add unit tests
  pkg/cloud/cloud.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, size/M

#200 Add verify target
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#201 Strip symbol for production build
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#131 Add snapshots support
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/cloud/mocks/mock_ec2.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: cncf-cla: yes, size/XL

#204 Rename verify-all file name
  Makefile
  hack/verify-all
Labels: approved, cncf-cla: yes, size/XS

#203 Fix race condition in DynamicallyProvisionedDeletePodTest
  tests/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#205 Update all unit tests to use go subtest
  pkg/cloud/cloud_test.go
  pkg/cloud/devicemanager/allocator_test.go
  pkg/cloud/metadata_test.go
  pkg/driver/controller_test.go
  pkg/driver/internal/inflight_test.go
Labels: approved, cncf-cla: yes, size/XL

#208 Fix link in readme
  docs/README.md
Labels: approved, cncf-cla: yes, size/M

#211 Create constants for keys used in map lookup
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/internal/inflight_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, size/L

#212 Use same mount to place in the csi.sock, remove obsolete volumes
  deploy/kubernetes/controller.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#209 Don't wait for the snapshot to be completed
  pkg/cloud/cloud.go
  pkg/driver/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#210 Add snapshot examples
  deploy/kubernetes/controller.yaml
  docs/README.md
  examples/kubernetes/snapshot/README.md
  examples/kubernetes/snapshot/claim.yaml
  examples/kubernetes/snapshot/pod.yaml
  examples/kubernetes/snapshot/restore-claim.yaml
  examples/kubernetes/snapshot/snapshot.yaml
  examples/kubernetes/snapshot/snapshotclass.yaml
  examples/kubernetes/snapshot/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#218 Merge snapshot to master branch
  deploy/kubernetes/controller.yaml
  docs/README.md
  examples/kubernetes/snapshot/README.md
  examples/kubernetes/snapshot/claim.yaml
  examples/kubernetes/snapshot/pod.yaml
  examples/kubernetes/snapshot/restore-claim.yaml
  examples/kubernetes/snapshot/snapshot.yaml
  examples/kubernetes/snapshot/snapshotclass.yaml
  examples/kubernetes/snapshot/storageclass.yaml
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/fakes.go
  pkg/cloud/mocks/mock_ec2.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#215 Implement raw block volume support
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, size/L

#219 Add unit tests for ControllerPublish and ControllerUnpublish requests
  pkg/driver/controller_test.go
  pkg/driver/fakes.go
  pkg/driver/node_test.go
  tests/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#222 Fake clean
  pkg/cloud/fakes.go
  pkg/cloud/metadata.go
  pkg/driver/controller_test.go
  pkg/driver/fakes.go
  pkg/driver/node_test.go
  tests/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, size/M

#227 Use default kubeconfig location
  tests/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#224 Fix bug in e2e test
  tests/e2e/testsuites/specs.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#226 New block volume e2e tests
  hack/feature-gates.yaml
  tests/e2e/dynamic_provisioning.go
  tests/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  tests/e2e/testsuites/specs.go
  tests/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#229 fix a bug when capacity range is nil
  pkg/driver/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S
