Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2020-05, with the labels that each got.

#491 Improve csi-snapshotter ClusterRole
  aws-ebs-csi-driver/templates/rbac.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#490 Update kubernetes-csi/external-snapshotter components to v2.1.1
  aws-ebs-csi-driver/templates/statefulset.yaml
  aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
  deploy/kubernetes/overlays/alpha/snapshot_controller.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#475 Generate deployment manifests from helm chart
  .travis.yml
  Makefile
  aws-ebs-csi-driver/Chart.yaml
  aws-ebs-csi-driver/templates/_helpers.tpl
  aws-ebs-csi-driver/templates/clusterrole-attacher.yaml
  aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml
  aws-ebs-csi-driver/templates/clusterrole-resizer.yaml
  aws-ebs-csi-driver/templates/clusterrole-snapshot-controller.yaml
  aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
  aws-ebs-csi-driver/templates/clusterrolebinding-attacher.yaml
  aws-ebs-csi-driver/templates/clusterrolebinding-provisioner.yaml
  aws-ebs-csi-driver/templates/clusterrolebinding-resizer.yaml
  aws-ebs-csi-driver/templates/clusterrolebinding-snapshot-controller.yaml
  aws-ebs-csi-driver/templates/clusterrolebinding-snapshotter.yaml
  aws-ebs-csi-driver/templates/controller.yaml
  aws-ebs-csi-driver/templates/csidriver.yaml
  aws-ebs-csi-driver/templates/node.yaml
  aws-ebs-csi-driver/templates/rbac.yaml
  aws-ebs-csi-driver/templates/role-snapshot-controller-leaderelection.yaml
  aws-ebs-csi-driver/templates/rolebinding-snapshot-controller-leaderelection.yaml
  aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
  aws-ebs-csi-driver/templates/serviceaccount-snapshot-controller.yaml
  aws-ebs-csi-driver/templates/statefulset.yaml
  deploy/kubernetes/base/clusterrole-attacher.yaml
  deploy/kubernetes/base/clusterrole-provisioner.yaml
  deploy/kubernetes/base/clusterrolebinding-attacher.yaml
  deploy/kubernetes/base/clusterrolebinding-provisioner.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/csidriver.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/rbac.yaml
  deploy/kubernetes/base/serviceaccount-csi-controller.yaml
  deploy/kubernetes/overlays/alpha/kustomization.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_resizer_clusterrole.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_resizer_clusterrolebinding.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_clusterrole.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_clusterrolebinding.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_leaderelection_role.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_leaderelection_rolebinding.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter_clusterrole.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter_clusterrolebinding.yaml
  deploy/kubernetes/overlays/alpha/serviceaccount-snapshot-controller.yaml
  deploy/kubernetes/overlays/alpha/snapshot_controller.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  deploy/kubernetes/values/controller.yaml
  deploy/kubernetes/values/node.yaml
  deploy/kubernetes/values/resizer.yaml
  deploy/kubernetes/values/snapshotter.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#495 Update stable overlay to 0.5.0
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#504 Fixed resizing docs to refer the right path to example spec
  examples/kubernetes/resizing/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#501 Add missing IAM permissions
  docs/example-iam-policy.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#508 Correct typo
  pkg/cloud/cloud_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#500 Fix migration test
  hack/run-e2e-test
Labels: approved, cncf-cla: yes, size/XS

#513 optimization: cache go mod during docker build
  Dockerfile
Labels: approved, cncf-cla: yes, size/XS
