Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2020-10, with the labels that each got.

#570 Add overlay for ECR images
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#574 Release v0.7.0
  CHANGELOG-0.x.md
  Makefile
  aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#573 Push amazonlinux target to Docker Hub
  .github/workflows/container-image.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#576 Post-release v0.7.0
  CHANGELOG-0.x.md
  aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#578 Fixing Helm install command
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#579 Fix markdown issue in README.md
  docs/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#582 Document behavior wrt minimum and maximum iops
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#568 Apply extra volume tags to EBS snapshots
  cmd/main.go
  cmd/options/controller_options.go
  cmd/options_test.go
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/driver_test.go
  pkg/driver/validation.go
  pkg/driver/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#585 Fixed image tag for helm chart values
  aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#577 [helm] add tag options and update csi-provisioner
  aws-ebs-csi-driver/Chart.yaml
  aws-ebs-csi-driver/templates/controller.yaml
  aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#593 Set CSIMigrationAWSComplete for migration tests
  tester/migration-test-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#602 Bump migration kops and k8s version
  hack/run-e2e-test
Labels: approved, cncf-cla: yes, lgtm, size/XS
