Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2020-04, with the labels that each got.

#479 Bump Go to 1.14.1
  .travis.yml
  Dockerfile
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#481 Add mount unittest
  pkg/driver/mount_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#478 Correct golint warning
  pkg/driver/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#484 Additional mount unittest
  pkg/driver/mount_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#486 docs/README: add missing "--namespace" flag to "helm" command
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#488 Add nodeAffinity to avoid Fargate worker nodes
  aws-ebs-csi-driver/templates/daemonset.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#489 *: remove deprecated "beta.kubernetes.io/os" nodeSelector
  aws-ebs-csi-driver/templates/daemonset.yaml
  aws-ebs-csi-driver/templates/deployment.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
