Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2020-11, with the labels that each got.

#618 Release v0.7.1
  Makefile
  aws-ebs-csi-driver/Chart.yaml
  aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#619 Post-release v0.7.1
  CHANGELOG-0.x.md
  Makefile
  aws-ebs-csi-driver/Chart.yaml
  aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#526 Chart option to disable default toleration of all taints
  aws-ebs-csi-driver/templates/controller.yaml
  aws-ebs-csi-driver/templates/node.yaml
  aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S
