Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2020-03, with the labels that each got.

#423 Update helm chart to better match available values and add the ability to add annotations
  .gitignore
  aws-ebs-csi-driver/Chart.yaml
  aws-ebs-csi-driver/templates/csidriver.yaml
  aws-ebs-csi-driver/templates/daemonset.yaml
  aws-ebs-csi-driver/templates/deployment.yaml
  aws-ebs-csi-driver/templates/manifest.yaml
  aws-ebs-csi-driver/templates/rbac.yaml
  aws-ebs-csi-driver/templates/serviceaccount.yaml
  aws-ebs-csi-driver/templates/statefulset.yaml
  aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#388 Update go mod and mount library
  Makefile
  go.mod
  go.sum
  hack/update-gomock
  hack/update-gomod
  hack/update-gomod.sh
  pkg/cloud/mocks/mock_ec2.go
  pkg/cloud/mocks/mock_ec2metadata.go
  pkg/driver/fakes.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/mocks/mock_metadata_service.go
  pkg/driver/mocks/mock_mounter.go
  pkg/driver/mount.go
  pkg/driver/node.go
  pkg/driver/sanity_test.go
  tester/multi-az-config.yaml
  tester/single-az-config.yaml
  tests/e2e-migration/hack/update-gomod.sh
  tests/e2e/dynamic_provisioning.go
  tests/e2e/suite_test.go
  tests/e2e/testsuites/testsuites.go
  tests/integration/setup_test.go
  tests/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, size/XXL

#456 Add release note for v0.5.0
  CHANGELOG-0.x.md
  Makefile
  hack/release
Labels: approved, cncf-cla: yes, size/M

#457 Add release workflow
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, size/M

#458 Bump version for v0.5.0 release
  CHANGELOG-0.x.md
  aws-ebs-csi-driver/Chart.yaml
  aws-ebs-csi-driver/values.yaml
  docs/design.md
Labels: approved, cncf-cla: yes, size/M

#459 Post release doc update
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: approved, cncf-cla: yes, size/S

#468 Fix e2e test
  tester/multi-az-config.yaml
  tester/single-az-config.yaml
Labels: approved, cncf-cla: yes, size/XS

#463 Update aws-sdk to v1.29.11 to get IMDSv2 support
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#460 Fixed typo in README
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#472 Adding amd64 as nodeSelector to avoid arm64 archtectures (#471)
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
