Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2020-12, with the labels that each got.

#630 Update ecr overlay image tag
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#632 Add cloudbuild.yaml for image pushing to gcr
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#616 Update hack/run-e2e-test to be more idempotent and pleasant to use
  hack/.gitignore
  hack/run-e2e-test
  hack/utils/helm.sh
  hack/utils/kops.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#623 Update chart repo index.yaml to contain all currently available chart versions
  index.yaml
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#634 Add latest tags to cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#629 docs(readme): update link to developer documentation
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#601 Fix the name of the snapshot controller leader election RoleBinding
  aws-ebs-csi-driver/templates/rolebinding-snapshot-controller-leaderelection.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_leaderelection_rolebinding.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#636 Fix target name in cloudbuild.yaml from amazon to amazonlinux
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#624 Move chart to charts directory and add workflow to publish new chart versions
  .github/workflows/helm-chart-release.yaml
  .github/workflows/release.yaml
  Makefile
  charts/aws-ebs-csi-driver/.helmignore
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/NOTES.txt
  charts/aws-ebs-csi-driver/templates/_helpers.tpl
  charts/aws-ebs-csi-driver/templates/clusterrole-attacher.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-resizer.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshot-controller.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-attacher.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-provisioner.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-resizer.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshot-controller.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshotter.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/csidriver.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/templates/role-snapshot-controller-leaderelection.yaml
  charts/aws-ebs-csi-driver/templates/rolebinding-snapshot-controller-leaderelection.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-snapshot-controller.yaml
  charts/aws-ebs-csi-driver/templates/statefulset.yaml
  charts/aws-ebs-csi-driver/values.yaml
  docs/README.md
  hack/run-e2e-test
  tester/migration-test-config.yaml
  tester/multi-az-config.yaml
  tester/single-az-config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#640 Apply resource constraints to all sidecar containers
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#639 Suffix amazonlinux image with -amazonlinux and push debian image to GitHub
  .github/workflows/container-image.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#641 Set up QEMU to build for arm64
  .github/workflows/container-image.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#642 Release v0.8.0
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/statefulset.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#644 Remove helm chart step from release github workflow and github registry step from container images workflow
  .github/workflows/container-image.yaml
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#649 Fix overlays not being updated for gcr migration
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#650 release-0.8: Remove helm chart step from release github workflow and github registry step from container images workflow
  .github/workflows/container-image.yaml
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#651 release-0.8: Fix overlays not being updated for gcr migration
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#648 Bring Go to 1.15.6 in Travis
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#638 Add self to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#658 Use buildx in cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#607 Update README.md
  examples/kubernetes/snapshot/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#647 Feature: Add ability to customize node daemonset nodeselector
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#659 (Try to) fix cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#661 Fix stray argument in cloudbuild.yaml
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#665 Add note for gp3 on outposts
  CHANGELOG-0.x.md
  docs/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#666 Call hack/prow.sh from cloudbuild
  cloudbuild.yaml
  hack/prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#668 cloudbuild: Set _STAGING_PROJECT
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
