Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-04, with the labels that each got.

#820 release v0.10.0
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#822 Warn users of migrating without draining
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#824 support volume partition
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/node.go
  pkg/driver/node_linux.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#826 Release 0.10.1
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/node.go
  pkg/driver/node_linux.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#827 release v0.10.1
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, size/S

#809 Cap IOPS when calculating from iopsPerGB
  docs/README.md
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/constants.go
  pkg/driver/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#831 update installation command to use latest stable version
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#832 update installation command to use latest stable version
  docs/README.md
Labels: approved, cncf-cla: yes, size/XS

#830 add options to enable aws sdk debug log and add more logs when driver…
  cmd/main.go
  cmd/options/controller_options.go
  cmd/options/controller_options_test.go
  cmd/options_test.go
  docs/README.md
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/devicemanager/manager.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/driver_test.go
  pkg/driver/node.go
  pkg/driver/node_linux.go
  pkg/mounter/safe_mounter_windows.go
  tests/e2e/dynamic_provisioning.go
  tests/e2e/pre_provsioning.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#835 update IAM policy sample and add new driver level tag
  docs/example-iam-policy.json
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/validation.go
  pkg/driver/validation_test.go
  tests/e2e/pre_provsioning.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#801 handling describe instances consistency issue
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/sanity_test.go
  tests/e2e/pre_provsioning.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#836 [helm/CSIDriver] Switch to non-deprecated apiVersion
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/csidriver.yaml
  deploy/kubernetes/base/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#834 Bump/reconcile sidecar versions in helm/kustomize
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#844 Update readme file to provide more info on driver options and tagging
  docs/README.md
Labels: approved, cncf-cla: yes, size/S

#842 Emit AWS API operation duration/error/throttle metrics
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
  cmd/main.go
  cmd/options/server_options.go
  pkg/cloud/aws_metrics.go
  pkg/cloud/cloud.go
  pkg/cloud/handlers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#849 Fix missing import
  pkg/cloud/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#851 Add additional logging for outpost arn handling
  pkg/cloud/metadata.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#850 Add empty StorageClasses to static example
  examples/kubernetes/static-provisioning/specs/example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#857 add pod disruption budget for csi controller
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller-poddisruptionbudget.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller-poddisruptionbudget.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#862 release v1.0.0
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#852 Add eksctl support to e2e scripts
  hack/e2e/ebs.sh
  hack/e2e/eksctl.sh
  hack/e2e/kops.sh
  hack/e2e/run.sh
  hack/e2e/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
