Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-02, with the labels that each got.

#700 Allow specifying --volume-attach-limit in the helm chart
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#710 release v0.9.0
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/arm64/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#713 Bump cloudbuild timeout to 1800s
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#715 Increase timout for cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#719 Remove arm overlay
  deploy/kubernetes/base/arm64/clusterrole-attacher.yaml
  deploy/kubernetes/base/arm64/clusterrole-provisioner.yaml
  deploy/kubernetes/base/arm64/clusterrolebinding-attacher.yaml
  deploy/kubernetes/base/arm64/clusterrolebinding-provisioner.yaml
  deploy/kubernetes/base/arm64/controller.yaml
  deploy/kubernetes/base/arm64/csidriver.yaml
  deploy/kubernetes/base/arm64/kustomization.yaml
  deploy/kubernetes/base/arm64/node.yaml
  deploy/kubernetes/base/arm64/serviceaccount-csi-controller.yaml
  deploy/kubernetes/overlays/stable/arm64/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#720 Move cr.yaml out of github workflows
  .github/cr.yaml
  .github/workflows/helm-chart-release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#718 release 0.9.0
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  cloudbuild.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#610 Add documentation for release process
  docs/README.md
  docs/RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#697 feat: Add option to provision StorageClasses
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/storageclass.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#724 Bump chart version
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#708 More controll over snapshot-controller scheduling
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#726 Integrate external e2e test in the testsuits
  Makefile
  tests/e2e-kubernetes/README.md
  tests/e2e-kubernetes/e2e_test.go
  tests/e2e-kubernetes/manifests.yaml
  tests/e2e-kubernetes/snapshotclass.yaml
  tests/e2e-kubernetes/storageclass.yaml
  tests/e2e-migration/README.md
  vendor/k8s.io/kubernetes/test/e2e/storage/external/BUILD
  vendor/k8s.io/kubernetes/test/e2e/storage/external/README.md
  vendor/k8s.io/kubernetes/test/e2e/storage/external/external.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#698 modify error message when request volume is in use with other node
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#731 Fix daemonset liveness image to multiarch version for ARM kustomization
  deploy/kubernetes/base/arm64/node.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#704 Add support for node existing service accounts
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/serviceaccount-csi-node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#730 Allow all fields to be set on StorageClasses
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#732 [chart] Allow resources override for node DaemonSet + priorityClassName
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/templates/statefulset.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#735 Updated installation to use latest 0.9 release
  docs/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, needs-ok-to-test, size/XS

#739 patch stable release to use gcr image
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#740 patch stable release to use gcr image
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#741 correct kustomization gcr image repo
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#742 correct kustomization gcr image repo
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#745 Update ECR overlay
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#711 Remove hardcoded snapshot controller image references
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/statefulset.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#744 Make CreateVolume idempotent
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/driver/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#734 [chart] Add storage class annotation and label handling
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/storageclass.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#702 Refactor inFlight key to add lock per volumeId
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/internal/inflight.go
  pkg/driver/internal/inflight_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#752 Set enableVolumeScheduling to true by default in the helm chart
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#759 Update test k8s version to 1.18.16
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#755 Sets the imagePullSecrets if the value is set in the chart
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#769 Aws client config: increase MaxRetries
  pkg/cloud/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#767 Fix error message when IOPSPerGB is missing in io1 volumes
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#756 Update livenessprobe image version from 2.1.0 to 2.2.0
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#771 delete leaked volume if driver don't know the volume status
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#762 add a document separator for storageclass template file
  charts/aws-ebs-csi-driver/templates/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#765 Allow setting http proxy and no proxy environment values
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/templates/statefulset.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#772 Update chart version
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
