Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-10, with the labels that each got.

#1078 Move mocks to parent package to avoid import cycle
  hack/update-gomock
  pkg/cloud/cloud_test.go
  pkg/cloud/ec2_interface.go
  pkg/cloud/metadata_interface.go
  pkg/cloud/metadata_test.go
  pkg/cloud/mock_cloud.go
  pkg/cloud/mock_ec2.go
  pkg/cloud/mock_metadata.go
  pkg/driver/controller_test.go
  pkg/driver/mock_mount.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1077 Release v1.3.1
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1080 deploy: Add resizer and snapshotter images to kustomization
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test
