Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-11, with the labels that each got.

#1109 Update to go 1.17
  Dockerfile
  go.mod
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/cespare/xxhash/v2/go.mod
  vendor/github.com/cespare/xxhash/v2/go.sum
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/hashicorp/golang-lru/go.mod
  vendor/github.com/jmespath/go-jmespath/go.mod
  vendor/github.com/jmespath/go-jmespath/go.sum
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.mod
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.sum
  vendor/github.com/moby/spdystream/go.mod
  vendor/github.com/moby/spdystream/go.sum
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/opencontainers/go-digest/go.mod
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/mount-utils/go.mod
  vendor/k8s.io/mount-utils/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1114 release 1.5.0
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
  examples/kubernetes/windows/README.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1113 Find volume path to expand device path in platform-agnostic way
  pkg/driver/node.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1118 [release-1.5] Post-release v1.5.0
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1103 Replace deprecated arg "--extra-volume-tags" by "--extra-tags"
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/_helpers.tpl
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1111 [chart] Allow installing snapshotter with storage.io API v1beta1
  charts/aws-ebs-csi-driver/templates/controller.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1125 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1126 images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved
