Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-07, with the labels that each got.

#960 [helm-chart] csi-snapshotter in ebs-csi-controller now checks for enableVolumeSnapshot before including it in containers
  charts/aws-ebs-csi-driver/templates/controller.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#967 Download fixed version of eksctl to avoid bugs
  hack/e2e/eksctl.sh
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#958 release-1.1: Release 1.1.1 and chart v1.2.4 with inFlight cache race fix
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/internal/inflight.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#959 Release v1.1.1 and chart v1.2.4
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#968 Install snapshot controller independently of helm for e2e tests
  Makefile
  hack/e2e/run.sh
  hack/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#971 Nit: Fix typo in the CHANGELOG
  CHANGELOG-0.x.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#970 Feature/allow add debug args
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#965 Several breaking changes to the helm chart
  Makefile
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/crds/snapshot-controller-crds.yaml
  charts/aws-ebs-csi-driver/templates/NOTES.txt
  charts/aws-ebs-csi-driver/templates/_helpers.tpl
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshot-controller.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-attacher.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-csi-node.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-provisioner.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-resizer.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshot-controller.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshotter.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/crds.yml
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml
  charts/aws-ebs-csi-driver/templates/poddisruptionbudget-snapshot-controller.yaml
  charts/aws-ebs-csi-driver/templates/role-snapshot-controller-leaderelection.yaml
  charts/aws-ebs-csi-driver/templates/rolebinding-snapshot-controller-leaderelection.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-snapshot-controller.yaml
  charts/aws-ebs-csi-driver/templates/snapshot-controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/clusterrole-snapshot-controller.yaml
  deploy/kubernetes/base/clusterrolebinding-snapshot-controller.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/poddisruptionbudget-snapshot-controller.yaml
  deploy/kubernetes/base/role-snapshot-controller-leaderelection.yaml
  deploy/kubernetes/base/rolebinding-snapshot-controller-leaderelection.yaml
  deploy/kubernetes/base/serviceaccount-snapshot-controller.yaml
  deploy/kubernetes/base/snapshot_controller.yaml
  deploy/kubernetes/values/snapshotter.yaml
  docs/README.md
  hack/values_eksctl.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#966 Update to csi-proxy v1 APIs
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  examples/kubernetes/windows/README.md
  go.mod
  go.sum
  hack/e2e/eksctl.sh
  hack/e2e/run.sh
  pkg/driver/node_windows.go
  pkg/mounter/safe_mounter_windows.go
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/Microsoft/go-winio/pipe.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta2/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta2/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1beta2/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/volume/v1beta2/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.mod
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.sum
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/disk/v1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/disk/v1beta2/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1beta1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/volume/v1beta2/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#972 Add how to consume new hack/e2e scripts in other repos (efs/fsx)
  hack/e2e/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#976 Updated README.md and changed the version in snapshot example
  .gitignore
  docs/README.md
  examples/kubernetes/dynamic-provisioning/README.md
  examples/kubernetes/snapshot/specs/classes/snapshotclass.yaml
  examples/kubernetes/snapshot/specs/snapshot-import/README.md
  examples/kubernetes/snapshot/specs/snapshot-import/static-snapshot/volume-snapshot-content.yaml
  examples/kubernetes/snapshot/specs/snapshot-import/static-snapshot/volume-snapshot.yaml
  examples/kubernetes/snapshot/specs/snapshot/snapshot.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#978 Updated default setting of windows daemon set
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#980 Increased the helm chart version
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#986 Update base images: yum update al2, bump debian tag
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#990 Release 1.1
  CHANGELOG-0.x.md
  Dockerfile
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#991 Release v1.1.3
  CHANGELOG-0.x.md
  Dockerfile
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#992 Release 1.1.3
  CHANGELOG-0.x.md
  Dockerfile
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#998 add ecr images to readme
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#999 release v1.2.0 - part 1
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: approved, cncf-cla: yes, size/M

#1004 release v1.2.0 - part 2
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, lgtm, size/S

#1005 Release v1.2.0
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#995 Update kustomize templates only after verifying images are available in registries
  docs/RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#988 [chart] Node update strategy & auto driver image tag
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
