Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-05, with the labels that each got.

#865 release v1.0.0
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#866 add self as owner
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#878 Fix kustomize RBAC bindings to have namespace kube-system
  Makefile
  deploy/kubernetes/base/clusterrolebinding-attacher.yaml
  deploy/kubernetes/base/clusterrolebinding-csi-node.yaml
  deploy/kubernetes/base/clusterrolebinding-provisioner.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_resizer_clusterrolebinding.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_clusterrolebinding.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_leaderelection_rolebinding.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter_clusterrolebinding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#879 release-1.0: Fix kustomize RBAC bindings to have namespace kube-system
  Makefile
  deploy/kubernetes/base/clusterrolebinding-attacher.yaml
  deploy/kubernetes/base/clusterrolebinding-csi-node.yaml
  deploy/kubernetes/base/clusterrolebinding-provisioner.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_resizer_clusterrolebinding.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_clusterrolebinding.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshot_controller_leaderelection_rolebinding.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter_clusterrolebinding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#874 fix naming mistake in clusterrolebinding, expose env var to controller via downward api
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-csi-node.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  deploy/kubernetes/base/clusterrolebinding-csi-node.yaml
  deploy/kubernetes/base/controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#881 bump helm chart version
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#882 fix naming mistake in clusterrolebinding, add env var to controller yaml
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-csi-node.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  deploy/kubernetes/base/clusterrolebinding-csi-node.yaml
  deploy/kubernetes/base/controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#891 deploy CSIDriver object api version dynamically based on kubeVersion
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/csidriver.yaml
  deploy/kubernetes/base/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#894 rename node clusterrolebinding to make auto upgrade work
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-csi-node.yaml
  deploy/kubernetes/base/clusterrolebinding-csi-node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#897 Only initialize the in-cluster kube client when metadata service is actually unavailable
  pkg/cloud/metadata.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#895 remove hardcoded namespace for pod disruption budget
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller-poddisruptionbudget.yaml
  deploy/kubernetes/base/controller-poddisruptionbudget.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#903 Reduce default log level to 2
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#906 Add pod disruption budgets that got missed in a rebase
  deploy/kubernetes/base/poddisruptionbudget-controller.yaml
  deploy/kubernetes/base/poddisruptionbudget-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
