Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-03, with the labels that each got.

#768 removed harcoded NAMESPACE from helm chart
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/NOTES.txt
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-attacher.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-provisioner.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-resizer.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshot-controller.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshotter.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/templates/role-snapshot-controller-leaderelection.yaml
  charts/aws-ebs-csi-driver/templates/rolebinding-snapshot-controller-leaderelection.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-snapshot-controller.yaml
  charts/aws-ebs-csi-driver/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#751 Add readiness probe so controller does not report "Ready" prematurely
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  deploy/kubernetes/base/controller.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#774 Add self as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#777 go mod tidy
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#778 Removing prestop hook for node-driver-registrar
  charts/aws-ebs-csi-driver/templates/node.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#776 add toleration time to NoExecute effect --- Enable in next release
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#779 Release 0.9.1
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  go.sum
  hack/e2e/run.sh
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  tests/e2e-kubernetes/README.md
  tests/e2e-kubernetes/e2e_test.go
  tests/e2e-kubernetes/manifests.yaml
  tests/e2e-kubernetes/snapshotclass.yaml
  tests/e2e-kubernetes/storageclass.yaml
  tests/e2e-migration/README.md
  vendor/k8s.io/kubernetes/test/e2e/storage/external/BUILD
  vendor/k8s.io/kubernetes/test/e2e/storage/external/README.md
  vendor/k8s.io/kubernetes/test/e2e/storage/external/external.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#780 Release 0.8.2
  .travis.yml
  CHANGELOG-0.x.md
  Dockerfile
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/clusterrole-attacher.yaml
  deploy/kubernetes/overlays/stable/arm64/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
  go.sum
  hack/e2e/.gitignore
  hack/e2e/README.md
  hack/e2e/ebs.sh
  hack/e2e/ecr.sh
  hack/e2e/helm.sh
  hack/e2e/kops.sh
  hack/e2e/run.sh
  hack/e2e/util.sh
  hack/run-e2e-test
  hack/run-integration-test
  hack/utils/kops.sh
  hack/utils/tiller-rbac.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  tester/migration-test-config.yaml
  tester/multi-az-config.yaml
  tester/single-az-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#787 hack/e2e: Support passing helm values as values.yaml and make other similar files optional
  hack/e2e/README.md
  hack/e2e/kops.sh
  hack/e2e/run.sh
  hack/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#789 Print csi plugin logs at end of e2e test
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#794 Remove storageclass from static example
  examples/kubernetes/static-provisioning/README.md
  examples/kubernetes/static-provisioning/specs/example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#773 Add well-known topology label
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#791 Update snapshot controller resources
  charts/aws-ebs-csi-driver/templates/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#802 Don't exit script prematurely if test fails
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#807 csi.storage.k8s.io/fstype is case sensitive
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#814 Use the old topology key for e2e tests
  tests/e2e/driver/ebs_csi_driver.go
  tests/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#808 fix deploy stable ecr error kustomization file
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#815 Track driver deploy time in e2e test pipeline
  hack/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#813 release v0.9.1
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#817 AWS EBS CSI Driver Helm chart to inject environment variables
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S
