Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-09, with the labels that each got.

#1039 [release-1.1] Automated cherry pick of #1019: Added Mount Idempotency
  pkg/cloud/aws_metrics.go
  pkg/driver/mocks/mock_mount.go
  pkg/driver/mount.go
  pkg/driver/node.go
  pkg/driver/node_linux.go
  pkg/driver/node_test.go
  pkg/driver/sanity_test.go
  pkg/mounter/safe_mounter_unix.go
  pkg/mounter/safe_mounter_windows.go
Labels: kind/bug, cncf-cla: yes, priority/critical-urgent, size/L, lgtm, approved, sig/storage, area/provider/aws, ok-to-test

#1037 [release-1.2] Automated cherry pick of #1019: Added Mount Idempotency
  pkg/cloud/aws_metrics.go
  pkg/driver/mocks/mock_mount.go
  pkg/driver/mount.go
  pkg/driver/mount_linux.go
  pkg/driver/mount_windows.go
  pkg/driver/node.go
  pkg/driver/node_linux.go
  pkg/driver/node_test.go
  pkg/driver/node_windows.go
  pkg/driver/sanity_test.go
  pkg/mounter/safe_mounter_unix.go
  pkg/mounter/safe_mounter_windows.go
Labels: kind/bug, cncf-cla: yes, priority/critical-urgent, size/L, lgtm, approved, sig/storage, area/provider/aws, ok-to-test

#1042 release v1.1.4
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1043 release 1.2.1
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1041 hash volume name to get client token
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1047 Fix windows build IsCorruptedMnt not implemented
  pkg/driver/mount_windows.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1049 [release-1.1] Increase prow timeout to 1h15m
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1055 1.1.4 post-release commit
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1056 1.2.1 post-release commit
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1058 merge patch commits back to master
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1035 Fix spacing in RELEASE.md
  docs/RELEASE.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1059 v1.3.0 release
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1060 Recognize instance-type node label when EC2 metadata isn't available
  pkg/cloud/metadata.go
  pkg/cloud/metadata_test.go
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#1051 [release-1.2] Automated cherry pick of #1041: hash volume name to get client token
  pkg/cloud/cloud.go
Labels: kind/bug, cncf-cla: yes, lgtm, priority/important-soon, size/XS, approved, sig/storage, area/provider/aws, ok-to-test

#1052 [release-1.2] Automated cherry pick of #1047: Fix windows build IsCorruptedMnt not implemented
  pkg/driver/mount_windows.go
Labels: kind/bug, cncf-cla: yes, lgtm, priority/important-soon, size/XS, approved, sig/storage, area/provider/aws, ok-to-test

#1045 [chart] Support image.pullPolicy for csi-resizer image
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1062 [release-1.2] Build and push multi-arch/os (amazon and windows, no debian) image manifest via Make rules
  .github/workflows/container-image.yaml
  Dockerfile
  Dockerfile.windows
  Makefile
  hack/e2e/ecr.sh
  hack/prow.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#1064 [release-1.2] Fix gcr prow and github builds: cherry-pick of #1016, #1017, and #1020
  .github/workflows/container-image.yaml
  cloudbuild.yaml
  hack/prow.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1067 post-release commit 1.3.0
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1068 merge 1.3.0 release and post-release commits into master
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/README.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1069 Allow default fstype to be overriden via values.yaml
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1070 Update windows example for image release
  examples/kubernetes/windows/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1074 Refactor pkg/cloud/metadata.go into pkg/cloud/metadata_*.go files
  hack/update-gomock
  pkg/cloud/cloud_interface.go
  pkg/cloud/metadata.go
  pkg/cloud/metadata_ec2.go
  pkg/cloud/metadata_interface.go
  pkg/cloud/metadata_k8s.go
  pkg/driver/mocks/mock_cloud.go
  pkg/driver/mocks/mock_metadata.go
  pkg/driver/mocks/mock_mount.go
  pkg/driver/mount.go
Labels: cncf-cla: yes, lgtm, approved, size/XL
