Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-12, with the labels that each got.

#1106 Support for custom labels
  charts/aws-ebs-csi-driver/templates/_helpers.tpl
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1124 add ecr-private kustomize overlay
  deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1132 Release v1.5.0
  CHANGELOG-0.x.md
  Makefile
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/README.md
  examples/kubernetes/windows/README.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1133 remove tag override from ecr overlay
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1134 Use TARGETOS/TARGETARCH in Dockerfile but OS/ARCH in Makefile
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#1135 PHONY make rules
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved

#1138 Simplify branch/version part of release process
  docs/RELEASE.md
  hack/release
Labels: cncf-cla: yes, lgtm, size/M, approved

#1054 [chart] Update kubernetes-csi/livenessprobe
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, kind/feature, size/S, lgtm, approved, ok-to-test

#1112 Add support for securityContext in controller
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1145 Fix the wrong app and helm chart version
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1141 Fix canonical nvme device resolution in more cases
  pkg/driver/node_linux.go
  pkg/driver/node_linux_test.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1151 [release-1.5] add ecr-private kustomize overlay and Update ECR sidecars to 1-18-13
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#1150 Update ECR sidecars to 1-18-13
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved
