Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2021-08, with the labels that each got.

#957 Build and push multi-arch/os (amazon and windows, no debian) image manifest via Make rules
  .github/workflows/container-image.yaml
  Dockerfile
  Dockerfile.windows
  Makefile
  examples/kubernetes/windows/README.md
  hack/e2e/ecr.sh
  hack/prow.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#1016 Fix github build failing because of wrong docker hub registry name
  .github/workflows/container-image.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1017 Fix gcr prow build failing because of IMAGE variable collision
  hack/prow.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1015 Update helm chart alongside kustomize, after images have been pushed, for consistency
  docs/RELEASE.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1008 [chart] Add controller strategy
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1020 Fix gcr prow builld failing because docker missing --os-version
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1021 Include ClusterRole and ClusterRoleBinding for csi-node
  deploy/kubernetes/base/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test
