Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2022-03, with the labels that each got.

#1176 Add self as OWNER
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1183 Update examples/kubernetes README files
  examples/kubernetes/block-volume/README.md
  examples/kubernetes/block-volume/manifests/claim.yaml
  examples/kubernetes/block-volume/manifests/pod.yaml
  examples/kubernetes/block-volume/manifests/storageclass.yaml
  examples/kubernetes/dynamic-provisioning/README.md
  examples/kubernetes/dynamic-provisioning/manifests/claim.yaml
  examples/kubernetes/dynamic-provisioning/manifests/pod.yaml
  examples/kubernetes/dynamic-provisioning/manifests/storageclass.yaml
  examples/kubernetes/resizing/README.md
  examples/kubernetes/resizing/manifests/claim.yaml
  examples/kubernetes/resizing/manifests/pod.yaml
  examples/kubernetes/resizing/manifests/storageclass.yaml
  examples/kubernetes/resizing/spec/example.yaml
  examples/kubernetes/snapshot/README.md
  examples/kubernetes/snapshot/manifests/app/claim.yaml
  examples/kubernetes/snapshot/manifests/app/pod.yaml
  examples/kubernetes/snapshot/manifests/classes/snapshotclass.yaml
  examples/kubernetes/snapshot/manifests/classes/storageclass.yaml
  examples/kubernetes/snapshot/manifests/snapshot-import/README.md
  examples/kubernetes/snapshot/manifests/snapshot-import/app/claim.yaml
  examples/kubernetes/snapshot/manifests/snapshot-import/app/pod.yaml
  examples/kubernetes/snapshot/manifests/snapshot-import/static-snapshot/volume-snapshot-content.yaml
  examples/kubernetes/snapshot/manifests/snapshot-import/static-snapshot/volume-snapshot.yaml
  examples/kubernetes/snapshot/manifests/snapshot-restore/claim.yaml
  examples/kubernetes/snapshot/manifests/snapshot-restore/pod.yaml
  examples/kubernetes/snapshot/manifests/snapshot/snapshot.yaml
  examples/kubernetes/static-provisioning/README.md
  examples/kubernetes/static-provisioning/manifests/claim.yaml
  examples/kubernetes/static-provisioning/manifests/pod.yaml
  examples/kubernetes/static-provisioning/manifests/pv.yaml
  examples/kubernetes/static-provisioning/specs/example.yaml
  examples/kubernetes/storageclass/README.md
  examples/kubernetes/storageclass/manifests/claim.yaml
  examples/kubernetes/storageclass/manifests/pod.yaml
  examples/kubernetes/storageclass/manifests/storageclass.yaml
  examples/kubernetes/storageclass/specs/example.yaml
  examples/kubernetes/windows/README.md
Labels: cncf-cla: yes, lgtm, approved, size/XL, ok-to-test

#1171 Update helm charts for a secrect exposure
  CHANGELOG-0.x.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1175 Fix nodeService.getVolumesLimit() adding more instance types
  pkg/cloud/metadata.go
  pkg/cloud/metadata_ec2.go
  pkg/cloud/metadata_interface.go
  pkg/cloud/metadata_k8s.go
  pkg/cloud/metadata_test.go
  pkg/cloud/mock_metadata.go
  pkg/cloud/volume_limits.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL, ok-to-test

#1188 prepare for release v1.5.2
  CHANGELOG-0.x.md
  Makefile
  docs/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1189 Fix windows mounting bug-1090
  pkg/mounter/safe_mounter_windows.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1194 Update deprecated command `go get`
  Makefile
  hack/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test
