Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2022-09, with the labels that each got.

#1370 Update module k8s.io/klog to v2
  cmd/main.go
  cmd/options.go
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/devicemanager/manager.go
  pkg/cloud/handlers.go
  pkg/cloud/metadata.go
  pkg/cloud/metadata_ec2.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/identity.go
  pkg/driver/internal/inflight.go
  pkg/driver/node.go
  pkg/driver/node_linux.go
  pkg/driver/node_windows.go
  pkg/driver/validation.go
  pkg/resizefs/resizefs_windows.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1375 Update the kustomization deployment to latest image tag
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1376 Updating static example to include setting fsType
  examples/kubernetes/static-provisioning/README.md
  examples/kubernetes/static-provisioning/manifests/pv.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1371 Add support for tuning leader election to the helm chart for csi-provisioner and csi-attacher
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1366 Support IOPS parameter for IO1/IO2 volumes
  docs/parameters.md
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  tests/e2e/driver/ebs_csi_driver.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1335 Add tags to snapshot based on VolumeSnapshotClass
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1384 Address CVEs
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, lgtm, approved

#1385 Release `v1.11.3`
  CHANGELOG.md
  Makefile
  README.md
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
Labels: cncf-cla: yes, size/S, do-not-merge/hold, lgtm, approved

#1387 Merge release 1.11 branch into master
  CHANGELOG.md
  Makefile
  README.md
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#1388 Release Helm chart `v2.11.0`
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1383 add link to install guide
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1391 Update release notes; Implement useOldCSIDriver parameter
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/csidriver.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1394 Update go version; Update dependencies
  .github/workflows/verify.yaml
  .gitignore
  Dockerfile
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved

#1379 Add initContainer parameter to the controller's template
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1398 Add resolver to handle custom endpoints
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1399 Add self to OWNERS
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1380 Add enableMetrics configuration
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/metrics.yaml
  charts/aws-ebs-csi-driver/values.yaml
  docs/metrics.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#1400 helm: Move default toleration to values.yaml so it can be overriden
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1404 Add snow device types to parameters
  docs/parameters.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1389 revise preqs for install docs
  docs/install.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1406 Release v1.11.4
  CHANGELOG.md
  Makefile
  README.md
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1401 Update workflows
  .github/workflows/codeql-analysis.yaml
  .github/workflows/trivy-containers.yaml
  .github/workflows/trivy.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#1407 Release `v1.11.4`
  .github/workflows/verify.yaml
  .gitignore
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved

#1403 Cleanup OWNERS
  OWNERS
Labels: cncf-cla: yes, size/S, lgtm, approved

#1411 Update `trivy.yaml` workflow event trigger
  .github/workflows/trivy.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved
