Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2022-07, with the labels that each got.

#1297 Add GitHub actions
  .github/workflows/codeql-analysis.yaml
  .github/workflows/release.yaml
  .github/workflows/unit-tests.yaml
  .github/workflows/verify.yaml
  pkg/mounter/mock_mount_windows.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1303 Fix version of K8s manifest images
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  deploy/kubernetes/secret.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1305 Fix image tags in ecr-public kustomization
  deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1306 Prepare for release v1.9.0
  CHANGELOG.md
  Makefile
  README.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1308 Post-release v1.9.0
  CHANGELOG.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1309 Release 1.9.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1313 Update install.md
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1312 add envFrom to container specs; sanitize comment with account info
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1319 Validate fs type before mounting
  pkg/driver/node.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1323 Pre-release v1.10.0
  CHANGELOG.md
  Makefile
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1325 Post-release v1.10.0
  CHANGELOG.md
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
  pkg/cloud/cloud.go
  pkg/cloud/devicemanager/allocator.go
  pkg/cloud/volume_limits.go
  pkg/mounter/safe_mounter_windows.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1324 Release 1.10
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
  pkg/cloud/cloud.go
  pkg/cloud/devicemanager/allocator.go
  pkg/cloud/volume_limits.go
  pkg/mounter/safe_mounter_windows.go
Labels: cncf-cla: yes, lgtm, size/M, approved
