Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2022-08, with the labels that each got.

#1330 Pass GOPROXY to image builder
  Dockerfile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1331 Set `GOPROXY` in `cloudbuild.yaml`
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1337 Fix static provisioning example
  examples/kubernetes/static-provisioning/README.md
  examples/kubernetes/static-provisioning/manifests/claim.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1329 Update kOps to `v1.23.0` + Update `parameters.md`
  Makefile
  docs/parameters.md
  hack/e2e/kops.sh
  hack/e2e/run.sh
  hack/kops-patch.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1334 Only run helm action when Chart.yaml modified
  .github/workflows/helm-chart-release.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1314 Enable EBS CSI driver for snow device
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/ec2_interface.go
  pkg/cloud/metadata.go
  pkg/cloud/metadata_ec2.go
  pkg/cloud/metadata_k8s.go
  pkg/cloud/metadata_test.go
  pkg/cloud/mock_ec2.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_linux.go
  pkg/driver/node_linux_test.go
  pkg/driver/node_test.go
  pkg/util/util.go
  tests/integration/setup_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1333 Improve securityContext implementation
  Makefile
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/poddisruptionbudget-controller.yaml
  deploy/kubernetes/base/serviceaccount-csi-controller.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1339 Automate publishing to ECR
  .github/workflows/publish-ecr.yaml
  Makefile
Labels: cncf-cla: yes, lgtm, size/M, approved

#1346 Set VERSION env variable in publish-ecr workflow
  .github/workflows/publish-ecr.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1348 Apply fix from helm chart to kustomize manifests
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1350 Automated cherry pick of #1348: Apply fix from helm chart to kustomize manifests
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1351 Explicitly pass VERSION as a build-arg
  .github/workflows/publish-ecr.yaml
  .github/workflows/release.yaml
  Dockerfile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1354 Release v1.11.2
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1349 Add kustomize verification for CI
  Makefile
  hack/verify-kustomize
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1356 Builds should not set/get GOPROXY in the environment
  CONTRIBUTING.md
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1358 c6i.metal and g5g.metal are nitro instances
  pkg/cloud/volume_limits.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1344 Example policy to support encrypted drives
  docs/install.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1359 Add warning message when region is unavailable on the controller
  pkg/driver/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1367 Update the kustomization deployment to latest image tag
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved
