Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2022-10, with the labels that each got.

#1408 Build Windows container for Windows Server 2022 LTSC
  Dockerfile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1409 Add support for io2 Block Express volumes
  docs/parameters.md
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/constants.go
  pkg/driver/controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1412 Release v1.12.0
  CHANGELOG.md
  Makefile
  README.md
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1413 Release v1.12.0
  CHANGELOG.md
  Makefile
  README.md
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1392 Add release and support policy to README.md
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1418 Add parameter to force enable snapshotter sidecar
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1419 Add serviceMonitor.labels parameter
  charts/aws-ebs-csi-driver/templates/metrics.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1341 Enable CI tests in K8s `1.25`
  Makefile
  go.mod
  go.sum
  hack/e2e/ebs.sh
  hack/e2e/run.sh
  hack/kops-patch-node.yaml
  hack/kops-patch.yaml
  hack/update-gomock
  pkg/driver/mock_mount.go
  pkg/driver/sanity_test.go
  pkg/mounter/safe_mounter_windows.go
  tests/e2e-kubernetes/README.md
  tests/e2e-kubernetes/e2e_test.go
  tests/e2e-kubernetes/manifests.yaml
  tests/e2e-kubernetes/snapshotclass.yaml
  tests/e2e-upgrade/README.md
  tests/e2e-upgrade/e2e_test.go
  tests/e2e-upgrade/kops.go
  tests/e2e/dynamic_provisioning.go
  tests/e2e/pre_provsioning.go
  tests/e2e/suite_test.go
  tests/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  tests/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
  tests/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
  tests/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
  tests/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  tests/e2e/testsuites/dynamically_provisioned_topology_aware_volume_tester.go
  tests/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  tests/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
  tests/e2e/testsuites/pre_provisioned_snapshot_volume_tester.go
  tests/e2e/testsuites/pre_provisioned_volume_tester.go
  tests/e2e/testsuites/specs.go
  tests/e2e/testsuites/testsuites.go
  tests/integration/integration_test.go
  tests/integration/setup_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved, ok-to-test

#1421 Update go version in unit-tests.yaml to 1.19
  .github/workflows/unit-tests.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1426 Add version information from tag to GCR build
  hack/prow.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1425 Release v1.12.1
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1427 refactor: Move the default controller tolerations in the helm chart values
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1429 [BUG] pkg/driver/controller.go uses ToLower
  pkg/driver/constants.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1430 Increase cloudbuild timeout
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1433 Upgrade dependencies
  Makefile
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: cncf-cla: yes, size/L, lgtm, approved
