Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2022-06, with the labels that each got.

#1257 Fix unable to create CSI snapshot-EBS csi driver
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/clusterrole-snapshotter.yaml
  deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1260 Bump up sidecar versions
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1262 Bump up helm chart to v2.6.9
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1269 Update parameters.md
  docs/install.md
  docs/parameters.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1270 Avoid git tag conflicts when vendoring hack/e2e in other repos (efs/fsx)
  hack/e2e/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1198 1182 quote extra tags arg
  charts/aws-ebs-csi-driver/templates/_helpers.tpl
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1272 Bump up Helm chart to v2.6.10
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1271 Upgrade eksctl to v0.101.0
  hack/e2e/eksctl.sh
  hack/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1280 Set handle-volume-inuse-error to false
  charts/aws-ebs-csi-driver/templates/controller.yaml
  deploy/kubernetes/base/controller.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1282 Prepare for release v1.7.0
  .github/workflows/release.yaml
  CHANGELOG.md
  Makefile
  README.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1283 Post-release v1.7.0
  .github/workflows/release.yaml
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1195 Support optional ec2 endpoint configuration
  charts/aws-ebs-csi-driver/templates/controller.yaml
  deploy/kubernetes/base/controller.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1276 Node driver registrar socket path fix
  charts/aws-ebs-csi-driver/templates/node.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1285 Bump up Helm chart to v2.7.0
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1233 Use minimal base image for linux builds
  Dockerfile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1165 Use k8s mount-utils for checking volume resize
  pkg/driver/mount_linux.go
  pkg/driver/node.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1290 Prepare for release v1.8.0
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#1292 Post-release v1.8.0
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1293 Release v1.8.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1277 Feature: Node affinity
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1295 Bump up Helm chart to v2.8.0
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved
