Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2023-10, with the labels that each got.

#1771 [release-1.22] Bump volume-modidifer-for-k8s sidecar to 0.1.3
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1772 [release-1.23] Bump volume-modidifer-for-k8s sidecar to 0.1.3
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1774 Release v1.23.1
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1775 Release 1.23
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1770 Refactor format option validation and tests
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1776 Add volume attachment limits for c7a instance family
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1777 Make capitalization of 'Inode' consistent
  docs/parameters.md
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  tests/e2e/format_options.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1779 CI: Fix 'error: externally-managed-environment'
  hack/e2e/chart-testing.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1778 Update GitHub workflows
  .github/workflows/generate-code-coverage.yaml
  .github/workflows/helm-chart-release.yaml
  .github/workflows/output-code-coverage.yaml
  .github/workflows/trivy-containers.yaml
  .github/workflows/trivy.yaml
  .github/workflows/unit-tests.yaml
  .github/workflows/verify.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1767 Metric Instrumentation Framework
  cmd/main.go
  pkg/cloud/aws_metrics.go
  pkg/cloud/cloud.go
  pkg/cloud/handlers.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1706 Support clustered allocation when formatting ext4 filesystem
  docs/faq.md
  docs/parameters.md
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  tests/e2e/format_options.go
  tests/e2e/testsuites/format_options_tester.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1781 Upgrade dependencies for release v1.24.0
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
  charts/aws-ebs-csi-driver/values.yaml
  cloudbuild.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/M, approved

#1782 Fix DeleteDisk error handling in volume creation failure
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1785 Release v1.24.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1787 Release 1.24
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1802 Correct 'Volume Resizing' feature in README.md
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1786 Add govulncheck and dependency-review to CI workflow
  .github/workflows/dependency-review.yaml
  .github/workflows/govulncheck.yaml
  Dockerfile
Labels: cncf-cla: yes, lgtm, size/M, approved

#1806 Disable `tolerateAllTaints` on kOps
  hack/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1809 Bump dependencies for release v1.23.2
  Dockerfile
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
  charts/aws-ebs-csi-driver/values.yaml
  cloudbuild.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  go.mod
  go.sum
  hack/e2e/chart-testing.sh
  hack/e2e/run.sh
  pkg/cloud/mock_ec2.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1805 Add compatibility workaround for A1 instance family
  Dockerfile
  Makefile
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/node.yaml
  hack/e2e/ecr.sh
Labels: cncf-cla: yes, lgtm, size/M, approved

#1811 [cherry-pick release-1.23] Add compatibility workaround for A1 instance family
  Dockerfile
  Makefile
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/node.yaml
  hack/e2e/ecr.sh
Labels: cncf-cla: yes, lgtm, size/M, approved

#1812 [cherry-pick release-1.24] Add compatibility workaround for A1 instance family
  Dockerfile
  Makefile
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/node.yaml
  hack/e2e/ecr.sh
Labels: cncf-cla: yes, lgtm, size/M, approved

#1817 Release aws-ebs-csi-driver v1.23.2
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1816 Update modify-volume.md
  docs/modify-volume.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test
