Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#1792 Add release scripts for upgrading sidecar dependencies and collating image digests
  .gitignore
  Makefile
  hack/release-scripts/generate-sidecar-tags
  hack/release-scripts/get-latest-sidecar-images
Labels: cncf-cla: yes, size/L, lgtm, approved

#1794 Add generate-release-pr to /hack/release-scripts
  hack/release-scripts/generate-release-pr
Labels: cncf-cla: yes, size/L, lgtm, approved

#1846 Add E2E tests for modifying volumes via annotations
  Makefile
  tests/e2e/modify_volume.go
  tests/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  tests/e2e/testsuites/e2e_utils.go
  tests/e2e/testsuites/format_options_tester.go
  tests/e2e/testsuites/modify_volume_tester.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1850 Enable CSI sanity/conformance tests
  Makefile
  go.mod
  go.sum
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/sanity_test.go
  tests/sanity/sanity_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1847 Add volume/snapshot tagging and FSR e2e tests
  hack/kops-patch.yaml
  pkg/driver/controller.go
  tests/e2e/driver/driver.go
  tests/e2e/driver/ebs_csi_driver.go
  tests/e2e/requires_aws_api.go
  tests/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
  tests/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  tests/e2e/testsuites/e2e_utils.go
  tests/e2e/testsuites/pre_provisioned_snapshot_volume_tester.go
  tests/e2e/testsuites/specs.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1859 Update getvolumeslimit
  pkg/cloud/metadata.go
  pkg/cloud/metadata_ec2.go
  pkg/cloud/metadata_interface.go
  pkg/cloud/metadata_k8s.go
  pkg/cloud/metadata_test.go
  pkg/cloud/mock_metadata.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1858 Bump otelhttp to fix CVE-2023-45142
  go.mod
  go.sum
  pkg/driver/driver.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1860 Bugfix: Instances listed under `maxVolumeLimits` not taking into account ENIs/Instance storage
  pkg/cloud/volume_limits.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1861 Add retry and background run to node taint removal
  pkg/driver/node.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1865 Add warning about --reuse-values to NOTES.txt
  charts/aws-ebs-csi-driver/templates/NOTES.txt
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1867 Upgrade dependencies ahead of aws-ebs-csi-driver v1.26.0
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/e2e/run.sh
  pkg/cloud/mock_ec2.go
  pkg/cloud/volume_limits.go
  pkg/driver/mock_k8s_client.go
  tests/e2e/testsuites/testsuites.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/XXL, lgtm, approved

#1872 Release aws-ebs-csi-driver v1.26.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1874 Release aws-ebs-csi-driver v1.26.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1877 CVE-2023-48795: bump golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#1879 Remove regression for GP3 storage classes below 3000 IOPS
  go.mod
  go.sum
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
