Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2023-03, with the labels that each got.

#1519 Add warning to README about k8s.gcr.io deprecation
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1520 [BACKPORT] k8s.gcr.io -> registry.k8s.io
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1523 Add support for XFS custom block sizes
  pkg/driver/node.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1525 Always log driver information
  pkg/driver/driver.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1528 Change README warning to new redirect announcement
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1529 Upgrade dependencies
  .github/workflows/unit-tests.yaml
  .github/workflows/verify.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/e2e/run.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#1532 Release v1.17.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1534 Release 1.17.0 (to master)
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1539 Kustomize: use 'resources' instead of deprecated 'bases'
  deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1533 Reduce scope of testing for test-helm-chart
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1540 Support VolumeSnapshotClass in Helm Chart
  charts/aws-ebs-csi-driver/templates/volumesnapshotclass.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1542 Add non-negative check on getVolumeLimit()
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1550 Clarify volume resizing in README; Remove Chrome(ium)-specific links
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1548 Fix VolumeSnapshotClass tagging
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1526 Fix staging / unmounting volume operations on Windows
  pkg/driver/mount_windows.go
  pkg/driver/node.go
  pkg/mounter/safe_mounter_windows.go
Labels: cncf-cla: yes, lgtm, size/M, approved
