Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2023-06, with the labels that each got.

#1614 Namespace-scoped leases permissions
  Makefile
  charts/aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml
  charts/aws-ebs-csi-driver/templates/role-leases.yaml
  charts/aws-ebs-csi-driver/templates/rolebinding-leases.yaml
  deploy/kubernetes/base/clusterrole-provisioner.yaml
  deploy/kubernetes/base/role-leases.yaml
  deploy/kubernetes/base/rolebinding-leases.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1567 Bump kOps k8s version to 1.27; Bump eksctl k8s version to 1.26
  hack/e2e/run.sh
  hack/kops-patch.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1627 Add additionalArgs parameter for sidecars
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#1621 Fix context handling in WaitForVolumeAttachment & add in-flight checks to attachment/detachment operations
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1630 Avoid generating manifests with empty envFrom fields
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1619 chore: Allow to set automountServiceAccountToken in ServiceAccount
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/serviceaccount-csi-controller.yaml
  deploy/kubernetes/base/serviceaccount-csi-node.yaml
  docs/install.md
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1626 Update DM allocator to use all available names
  pkg/cloud/cloud_test.go
  pkg/cloud/devicemanager/allocator.go
  pkg/cloud/devicemanager/allocator_test.go
  pkg/cloud/devicemanager/device_names.go
  pkg/cloud/devicemanager/manager.go
  pkg/cloud/devicemanager/manager_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1637 Upgrade dependencies
  go.mod
  go.sum
  hack/e2e/run.sh
  pkg/cloud/mock_ec2.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1634 Extend resource list in Kustomization file
  deploy/kubernetes/base/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1654 Release 1.20
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved
