Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2023-09, with the labels that each got.

#1734 Temporarily workaround Windows e2e failures with larger instance type and slimmer AMI
  hack/e2e/eksctl.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1722 Additional DaemonSets feature
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/node.yaml
  docs/additional-daemonsets.md
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1735 Add kustomize e2e test
  Makefile
  hack/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/M, approved

#1737 Update OWNERS
  OWNERS
Labels: cncf-cla: yes, size/S, lgtm, approved

#1739 Additional Node DaemonSets bug fixes
  charts/aws-ebs-csi-driver/templates/node-windows.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  docs/additional-daemonsets.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1736 PreStop lifecycle hook feature
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/clusterrole-csi-node.yaml
  cmd/hooks/prestop.go
  cmd/hooks/prestop_test.go
  cmd/options.go
  deploy/kubernetes/base/clusterrole-csi-node.yaml
  deploy/kubernetes/base/node.yaml
  hack/update-gomock
  pkg/driver/mock_k8s_storagev1.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1738 Display verbose output for test-helm-chart CI job
  tests/ct-config.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1732 Manage DaemonSets enablement
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1741 Do not call ModifyVolume if the volume is already in the desired state
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1743 Add dependancy upgrades for driver v1.23
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  go.mod
  go.sum
  hack/e2e/run.sh
  pkg/cloud/mock_ec2.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1745 Switch to new s3 bucket in AWS community account
  hack/e2e/metrics/metrics.sh
  hack/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1744 Cherry pick of 0a1b70c792226d5ac31b33b6f21eee25a5bc24b1 to release-1.22
  hack/e2e/eksctl.sh
  hack/e2e/run.sh
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1742 Add volume limits for m7a, c7i, r7a, r7iz instance families
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1751 Update default API version for PodDisruptionBudget
  charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1754 feat(helm): add labels to volumesnapshotclass
  charts/aws-ebs-csi-driver/templates/volumesnapshotclass.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, tide/merge-method-squash, lgtm, size/XS, approved, ok-to-test

#1756 Change chart-releaser-action config to not set Helm Chart releases as default
  .github/workflows/helm-chart-release.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1716 Make hostNetwork configurable for daemonset
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, tide/merge-method-squash, lgtm, size/XS, approved, ok-to-test

#1753 [ebs-csi-controller] Allow passing template value for clusterName
  charts/aws-ebs-csi-driver/templates/controller.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1757 feat(helm): add to additionalClusterRoleRules to sidecar chart templates
  charts/aws-ebs-csi-driver/templates/clusterrole-attacher.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-resizer.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1755 Update static-provisioning example README.md
  examples/kubernetes/static-provisioning/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1758 Fix go.mod indirect versions
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1762 Add Github actions code coverage CI job
  .github/workflows/generate-code-coverage.yaml
  .github/workflows/output-code-coverage.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#1764 Document topologies in parameters.md
  docs/parameters.md
Labels: cncf-cla: yes, lgtm, size/M, approved
