Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-05, with the labels that each got.

#2022 Inject volumeWaitParameters dependency
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/retry_manager.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2028 `Makefile` & `hack/` Process Improvements
  Makefile
  docs/makefile.md
  hack/e2e/build-image.sh
  hack/e2e/config.sh
  hack/e2e/create-cluster.sh
  hack/e2e/eksctl/cluster.yaml
  hack/e2e/eksctl/eksctl.sh
  hack/e2e/eksctl/patch.yaml
  hack/e2e/kubeconfig.sh
  hack/e2e/run.sh
  hack/prow-e2e.sh
  hack/tools/install.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#2025 Replace coalescer implementation with new coalescer package
  pkg/driver/controller.go
  pkg/driver/controller_modify_volume.go
  pkg/driver/controller_test.go
  pkg/driver/request_coalescing_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2029 Tune batcher EC2 Describe* delays
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#2038 Address GO-2024-2824
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2035 Make scrape interval configurable
  charts/aws-ebs-csi-driver/templates/metrics.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, tide/merge-method-squash, lgtm, size/XS, approved, ok-to-test

#2012 chore: add requirements.in files with fixed versions to use in pip
  hack/tools/aws-requirements.in
  hack/tools/install.sh
  hack/tools/yamale-requirements.in
  hack/tools/yamllint-requirements.in
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, ok-to-test

#2034 Expose dnsConfig in Helm Chart for Custom DNS Configuration
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, tide/merge-method-squash, lgtm, size/XS, approved, ok-to-test

#2037 Sanitize CSI RPC request logs
  pkg/driver/controller.go
  pkg/driver/node.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2039 Add `defaultStorageClass` parameter
  charts/aws-ebs-csi-driver/templates/ebs-csi-default-sc.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2040 Pin kubetest2 dependency
  hack/tools/install.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2041 Upgrade dependencies
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  go.mod
  go.sum
  hack/tools/install.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#2042 Release v1.31.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2043 Release 1.31
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2048 Switch to AWS CLI v2
  hack/tools/aws-requirements.in
  hack/tools/install.sh
Labels: cncf-cla: yes, lgtm, size/M, approved
