Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-12, with the labels that each got.

#2247 Fix supported filesystem types
  docs/parameters.md
  pkg/driver/constants.go
  pkg/driver/node.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#2248 Update metrics to align with Prometheus best practices
  charts/aws-ebs-csi-driver/values.yaml
  cmd/main.go
  docs/metrics.md
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/handlers.go
  pkg/driver/options.go
  pkg/driver/options_test.go
  pkg/metrics/metrics.go
  pkg/metrics/nvme.go
  pkg/metrics/nvme_test.go
  tests/e2e/dynamic_provisioning.go
  tests/e2e/nvme_metrics.go
  tests/e2e/pre_provsioning.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2250 enabling node metrics causes helm apply failure on malformed yaml
  charts/aws-ebs-csi-driver/templates/metrics.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2256 Remove duplicate 'enableMetrics' key
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2259 Bump dependencies for release v1.38.0
  charts/aws-ebs-csi-driver/values.yaml
  cloudbuild.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/tools/install.sh
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, kind/feature, size/L, lgtm, approved

#2261 Release v1.38.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#2264 Finalize Release 1.38
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#2244 Add FIPS image and Helm option
  Dockerfile
  Makefile
  charts/aws-ebs-csi-driver/templates/_helpers.tpl
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  docs/fips.md
  docs/makefile.md
  hack/cloudbuild.sh
Labels: cncf-cla: yes, lgtm, size/M, approved

#2268 Update metrics.md to included quick start for node.enableMetrics
  docs/metrics.md
Labels: cncf-cla: yes, size/S, kind/documentation, lgtm, approved, ok-to-test

#2270 Fixup FIPS Makefile/E2E
  Makefile
  hack/e2e/build-image.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2253 Selinux Mount Option
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, kind/feature, size/S, lgtm, approved
