Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-07, with the labels that each got.

#2078 Add fix for enableLinux node parameter
  charts/aws-ebs-csi-driver/templates/_node.tpl
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2080 Bump go version to fix govulncheck failure
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2079 Developer Experience Improvements
  CONTRIBUTING.md
  Dockerfile
  Makefile
  cloudbuild.yaml
  docs/makefile.md
  hack/cloudbuild.sh
  hack/e2e/build-image.sh
  hack/e2e/install.sh
  hack/e2e/run.sh
  hack/e2e/uninstall.sh
  hack/e2e/util.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#2075 Use new client token when `CreateVolume` returns `IdempotentParameterMismatch`
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/devicemanager/allocator.go
  pkg/cloud/devicemanager/allocator_test.go
  pkg/cloud/devicemanager/manager.go
  pkg/cloud/devicemanager/manager_test.go
  pkg/expiringcache/expiring_cache.go
  pkg/expiringcache/expiring_cache_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2081 Add --kubeconfig flag for out-of-cluster auth
  cmd/main.go
  pkg/cloud/metadata/k8s.go
  pkg/driver/options.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2083 Change coalescer InputType from `comparable` to `any`
  pkg/coalescer/coalescer.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#2084 fix dnsConfig indentation in controller template file
  charts/aws-ebs-csi-driver/templates/controller.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-ok-to-test

#2085 govulncheck: Bump google.golang.org/grpc to v1.64.1
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2088 fix function name in comment
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2082 Modifying Tags On Existing Volume
  docs/example-iam-policy.json
  docs/tagging.md
  examples/kubernetes/modify-volume/README.md
  examples/kubernetes/modify-volume/manifests/volumeattributesclass.yaml
  hack/e2e/kops/patch-cluster.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/ec2_interface.go
  pkg/cloud/interface.go
  pkg/cloud/mock_cloud.go
  pkg/cloud/mock_ec2.go
  pkg/driver/controller.go
  pkg/driver/controller_modify_volume.go
  pkg/driver/controller_modify_volume_test.go
  pkg/driver/request_coalescing_test.go
  tests/e2e/modify_volume.go
  tests/e2e/testsuites/e2e_utils.go
  tests/e2e/testsuites/modify_volume_tester.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/L, lgtm, approved, ok-to-test

#2086 Migrate CreateVolume response topology to standard label topology.kubernetes.io/zone
  examples/kubernetes/static-provisioning/README.md
  examples/kubernetes/static-provisioning/manifests/pv.yaml
  examples/kubernetes/storageclass/manifests/storageclass.yaml
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  tests/e2e/driver/ebs_csi_driver.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2091 Bump GCR sidecars that reference broken tags
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, lgtm, approved

#2094 bump dependencies for driver release v1.33.0
  charts/aws-ebs-csi-driver/values.yaml
  cloudbuild.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  go.mod
  go.sum
  hack/tools/install.sh
  pkg/cloud/volume_limits.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/identity.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/L, lgtm, approved, ok-to-test

#2095 [cherry-pick] Bump GCR sidecars that reference broken tags
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2097 Release v1.33.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, tide/merge-method-squash, lgtm, size/M, approved, ok-to-test

#2098 Finalize Release v1.33.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2102 fix: sidecars.snapshotter.logLevel not being respect
  charts/aws-ebs-csi-driver/templates/controller.yaml
  deploy/kubernetes/base/controller.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test
