Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-04, with the labels that each got.

#1963 Migrate to AWS SDKv2
  go.mod
  go.sum
  hack/update-mockgen.sh
  pkg/cloud/cloud.go
  pkg/cloud/cloud_interface.go
  pkg/cloud/cloud_test.go
  pkg/cloud/devicemanager/manager.go
  pkg/cloud/devicemanager/manager_test.go
  pkg/cloud/ec2_interface.go
  pkg/cloud/handlers.go
  pkg/cloud/metadata.go
  pkg/cloud/metadata_ec2.go
  pkg/cloud/metadata_interface.go
  pkg/cloud/metadata_test.go
  pkg/cloud/mock_cloud.go
  pkg/cloud/mock_ec2.go
  pkg/cloud/mock_metadata.go
  pkg/driver/controller.go
  pkg/driver/controller_modify_volume.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_linux_test.go
  pkg/driver/node_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/e2e/requires_aws_api.go
  tests/e2e/testsuites/e2e_utils.go
  tests/e2e/testsuites/testsuites.go
  tests/integration/README.md
  tests/integration/integration_test.go
  tests/integration/setup_test.go
  tests/sanity/sanity_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1965 Batch polling of DescribeVolumesModifications
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1996 Fix CVE G0-2024-2687 by bumping go and /x/net dependencies
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2000 Fix DeleteSnapshot error message
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2005 Add explicit `AttachVolume` call in `WaitForAttachmentState`
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#2006 Add IMDSv2 support to FAQ
  docs/faq.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2007 Handle deleted Node case in hook; Add support for CAS taint
  cmd/hooks/prestop.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1995 Improve configuration management; Improve the relationship between driver, controller, & cloud
  Makefile
  cmd/main.go
  cmd/options.go
  cmd/options/controller_options.go
  cmd/options/controller_options_test.go
  cmd/options/node_options.go
  cmd/options/node_options_test.go
  cmd/options/server_options.go
  cmd/options/server_options_test.go
  cmd/options_test.go
  docs/options.md
  go.mod
  go.sum
  hack/update-mockgen.sh
  pkg/cloud/interface.go
  pkg/cloud/metadata/ec2.go
  pkg/cloud/metadata/interface.go
  pkg/cloud/metadata/k8s.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/metadata_test.go
  pkg/cloud/metadata/mock_metadata.go
  pkg/cloud/mock_cloud.go
  pkg/driver/controller.go
  pkg/driver/controller_modify_volume.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/driver_test.go
  pkg/driver/node.go
  pkg/driver/node_linux_test.go
  pkg/driver/node_test.go
  pkg/driver/options.go
  pkg/driver/options_test.go
  pkg/driver/request_coalescing_test.go
  pkg/driver/validation.go
  pkg/driver/validation_test.go
  tests/sanity/sanity_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/XXL, lgtm, approved

#2009 Remove DeleteDisk call in CreateDisk path
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#2014 Add CLI options to run metrics endpoint over HTTPS
  cmd/main.go
  docs/options.md
  pkg/driver/options.go
  pkg/driver/options_test.go
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2013 Consolidate request handling in RecordRequestsMiddleware
  pkg/cloud/cloud.go
  pkg/cloud/handlers.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2015 Run taint removal only if Kubernetes API is available
  pkg/driver/node.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#2016 Upgrade dependencies
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/tools/install.sh
  pkg/cloud/volume_limits.go
  pkg/driver/mock_k8s_client.go
  tests/e2e/testsuites/testsuites.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2019 Release driver v1.30.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2020 Release 1.30
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2017 Remove old and unused promotion pipeline
  .github/workflows/publish-ecr.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#2018 Auto-discover cluster version in Helm test pod
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2021 Decrease dynamic provisioning time by 1.5 seconds
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2011 Add Alpha Support for Windows HostProcess Containers
  Dockerfile
  Makefile
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  cmd/main.go
  go.mod
  go.sum
  hack/e2e/run.sh
  hack/prow-e2e.sh
  hack/update-mockgen.sh
  pkg/cloud/metadata/k8s.go
  pkg/driver/driver.go
  pkg/driver/options.go
  pkg/mounter/mock_mount_windows.go
  pkg/mounter/mount.go
  pkg/mounter/mount_linux.go
  pkg/mounter/mount_linux_test.go
  pkg/mounter/mount_windows.go
  pkg/mounter/mount_windows_proxyV1.go
  pkg/mounter/mount_windows_proxyV2.go
  pkg/mounter/safe_mounter.go
  pkg/mounter/safe_mounter_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#2024 Implement separate coalescer package and unit tests
  pkg/coalescer/coalescer.go
  pkg/coalescer/coalescer_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved
