Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#2205 Fix typo
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved, ok-to-test

#2212 Set image.pullPolicy to Always for Makefile installations
  hack/e2e/util.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2213 Update patch-cluster.yaml to v1beta1 for Vac
  hack/e2e/kops/patch-cluster.yaml
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2208 Upgrade Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, size/S, kind/cleanup, lgtm, approved

#2216 Expose NVMe Volume Metrics
  Makefile
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/metrics.yaml
  cmd/main.go
  deploy/kubernetes/base/node.yaml
  go.mod
  pkg/driver/node.go
  pkg/driver/options.go
  pkg/driver/options_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/nvme.go
  pkg/metrics/nvme_test.go
  pkg/metrics/nvme_windows.go
  tests/e2e/nvme_metrics.go
  tests/e2e/testsuites/testsuites.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/XXL, lgtm, approved

#2219 Fixup trivy workflows
  .github/workflows/trivy-containers.yaml
  .github/workflows/trivy.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2222 Update anti-affinity
  charts/aws-ebs-csi-driver/templates/node.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2215 Add helm chart configuration to add init containers to the node daemonset
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2223 Upgrade dependencies
  charts/aws-ebs-csi-driver/values.yaml
  go.mod
  go.sum
  hack/tools/install.sh
  pkg/mounter/mount_linux.go
  pkg/mounter/mount_windows.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2224 Release v1.37.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2226 Release 1.37
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2230 Fix Trivy TOOMANYREQUESTS errors
  .github/workflows/trivy-containers.yaml
  .github/workflows/trivy.yaml
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2240 Enable VAC feature gate for Kustomize deployments
  deploy/kubernetes/base/controller.yaml
  hack/update-kustomize.sh
Labels: cncf-cla: yes, kind/feature, lgtm, size/XS, approved

#2243 Add tpl to serviceAccount annotations
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
Labels: cncf-cla: yes, kind/feature, lgtm, size/XS, approved
