Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-08, with the labels that each got.

#2103 Ensure ModifyVolume returns InvalidArgument error code if VAC contains invalid parameter
  pkg/driver/controller_modify_volume.go
  pkg/driver/controller_modify_volume_test.go
  tests/e2e/modify_volume.go
  tests/e2e/testsuites/e2e_utils.go
  tests/e2e/testsuites/modify_volume_tester.go
Labels: cncf-cla: yes, tide/merge-method-squash, lgtm, size/M, approved, ok-to-test

#2089 add more unit tests to increase test coverage
  pkg/cloud/cloud_test.go
  pkg/driver/controller_modify_volume_test.go
  pkg/driver/controller_test.go
  pkg/driver/driver_test.go
  pkg/driver/validation.go
  pkg/driver/validation_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2106 Add nodeComponentOnly parameter to helm chart
  charts/aws-ebs-csi-driver/templates/clusterrole-attacher.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-resizer.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-attacher.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-provisioner.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-resizer.yaml
  charts/aws-ebs-csi-driver/templates/clusterrolebinding-snapshotter.yaml
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/templates/csidriver.yaml
  charts/aws-ebs-csi-driver/templates/ebs-csi-default-sc.yaml
  charts/aws-ebs-csi-driver/templates/metrics.yaml
  charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml
  charts/aws-ebs-csi-driver/templates/role-leases.yaml
  charts/aws-ebs-csi-driver/templates/rolebinding-leases.yaml
  charts/aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#2108 Fix gpus not being considered when counting allocatables
  hack/generate-gpu-count-table.sh
  hack/generate-instance-store-table.sh
  pkg/cloud/volume_limits.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/L, lgtm, approved, ok-to-test

#2109 Add toggle for PodDisruptionBudget in chart
  charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2112 Automatically update RBAC in `make update-sidecar-dependencies`
  charts/aws-ebs-csi-driver/templates/clusterrole-attacher.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-resizer.yaml
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
  deploy/kubernetes/base/clusterrole-attacher.yaml
  deploy/kubernetes/base/clusterrole-provisioner.yaml
  deploy/kubernetes/base/clusterrole-resizer.yaml
  deploy/kubernetes/base/clusterrole-snapshotter.yaml
  hack/release-scripts/generate-sidecar-tags
  hack/release-scripts/get-latest-sidecar-images
  hack/release-scripts/image-digests-template.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved

#2114 Auto-enable VAC on clusters with beta API version
  charts/aws-ebs-csi-driver/templates/controller.yaml
  docs/modify-volume.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#2115 Fix accelerators not being considered when counting allocatables
  hack/generate-gpu-count-table.sh
  hack/generate-instance-store-table.sh
  pkg/cloud/volume_limits.go
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2116 Fix spelling errors in volume_limits.go comments
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2118 Backout VAC auto-enable
  charts/aws-ebs-csi-driver/templates/controller.yaml
  docs/modify-volume.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#2117 Document metadata requirement and available sources
  docs/install.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#2123 Upgrade dependencies ahead of v1.34.0
  .github/workflows/generate-code-coverage.yaml
  .github/workflows/govulncheck.yaml
  .github/workflows/output-code-coverage.yaml
  .github/workflows/trivy-containers.yaml
  .github/workflows/unit-tests.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/tools/install.sh
  pkg/driver/node.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2125 Fix github action CI permissions
  .github/workflows/helm-chart-release.yaml
  .github/workflows/release.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2126 Release aws-ebs-csi-driver v1.34.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2129 Release v1.34.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2131 Update faq.md with Karpenter best practices
  docs/faq.md
Labels: cncf-cla: yes, lgtm, size/XS, approved
