Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-01, with the labels that each got.

#1886 Update driver dependencies
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#1887 Release aws-ebs-csi-driver v1.26.1
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1888 Release 1.26.1
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1856 Refactor the Makefile and hack/ scripts
  .dockerignore
  .github/workflows/publish-ecr.yaml
  .gitignore
  Dockerfile
  Makefile
  deploy/kubernetes/base/clusterrolebinding-attacher.yaml
  deploy/kubernetes/base/clusterrolebinding-csi-node.yaml
  deploy/kubernetes/base/clusterrolebinding-provisioner.yaml
  deploy/kubernetes/base/clusterrolebinding-resizer.yaml
  deploy/kubernetes/base/clusterrolebinding-snapshotter.yaml
  docs/makefile.md
  hack/.gitignore
  hack/e2e/README.md
  hack/e2e/chart-testing.sh
  hack/e2e/config.sh
  hack/e2e/create-cluster.sh
  hack/e2e/delete-cluster.sh
  hack/e2e/ecr.sh
  hack/e2e/eksctl/eksctl.sh
  hack/e2e/eksctl/patch.yaml
  hack/e2e/eksctl/values.yaml
  hack/e2e/eksctl/vpc-resource-controller-configmap.yaml
  hack/e2e/helm.sh
  hack/e2e/kops/kops.sh
  hack/e2e/kops/patch-cluster.yaml
  hack/e2e/kops/patch-node.yaml
  hack/e2e/kops/values.yaml
  hack/e2e/metrics/metrics.sh
  hack/e2e/run.sh
  hack/provenance.sh
  hack/prow-e2e.sh
  hack/prow.sh
  hack/release
  hack/release-scripts/generate-release-pr
  hack/release-scripts/generate-sidecar-tags
  hack/release-scripts/get-latest-sidecar-images
  hack/tools/install.sh
  hack/tools/python-runner.sh
  hack/update-gofmt
  hack/update-gomock
  hack/update-gomod
  hack/update-kustomize.sh
  hack/update-mockgen.sh
  hack/verify-all
  hack/verify-gofmt
  hack/verify-govet
  hack/verify-update.sh
  hack/verify-vendor.sh
Labels: cncf-cla: yes, size/XXL, lgtm, approved

#1883 Remove premature CreateVolume error if requested IOPS is below minimum
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1890 Add ext3 and xfs fsTypes to e2e format-option test coverage
  tests/e2e/format_options.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1891 Add ext3 test coverage to our e2e-kubernetes storage conformance tests
  tests/e2e-kubernetes/manifests.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1871 Enable kubetest2 container logs for pull-aws-ebs-csi-driver-test-helm-chart
  hack/e2e/run.sh
  tests/ct-config.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1878 Use lsblk to safeguard against outdated symlinks
  pkg/driver/node_linux.go
  pkg/driver/node_linux_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1857 Add attachment limit scripts to hack/cluster-debugging-scripts
  hack/cluster-debugging-scripts/README.md
  hack/cluster-debugging-scripts/device_slot_test.tmpl
  hack/cluster-debugging-scripts/find-attachment-limit
  hack/cluster-debugging-scripts/generate_example_manifest.go
  hack/cluster-debugging-scripts/get-attachment-breakdown
  hack/cluster-debugging-scripts/go.mod
Labels: cncf-cla: yes, size/L, lgtm, approved

#1897 Add a1compat image to publish-ecr github action
  .github/workflows/publish-ecr.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1889 Remember likely bad device names for an hour
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/devicemanager/allocator.go
  pkg/cloud/devicemanager/allocator_test.go
  pkg/cloud/devicemanager/manager.go
  pkg/cloud/devicemanager/manager_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1898 Fix taint removal retry for non-swallowed errors
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1900 Bump go/sidecar dependencies ahead of v1.27.0
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  go.mod
  go.sum
  pkg/driver/controller.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1840 fix: Add parameters for tuning revisionHistoryLimit and emptyDir volumes
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1902 Bootstrap buildx builder in prow.sh
  hack/prow.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1903 Bump volume-modifier-for-k8s to v0.2.1
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1907 Pin metrics server version; Fix minor `make cluster/create` bug
  Makefile
  hack/e2e/metrics/metrics.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1904 Release v1.27.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1908 Release 1.27.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
  hack/e2e/metrics/metrics.sh
Labels: cncf-cla: yes, lgtm, size/M, approved

#1910 Update release-script to use new makefile target
  hack/release-scripts/generate-release-pr
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1894 Add scalability section to FAQ
  README.md
  docs/faq.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#1912 Fix Trivy image scanner
  .github/workflows/trivy-containers.yaml
  .github/workflows/trivy.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved
