Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-03, with the labels that each got.

#1950 Add OS topology key to node segments map
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  tests/e2e/driver/ebs_csi_driver.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1953 Fix Small Papercuts 2.0
  README.md
  cmd/options.go
  cmd/options_test.go
  hack/e2e/kops/kops.sh
  hack/release-scripts/generate-release-pr
Labels: cncf-cla: yes, size/L, lgtm, approved

#1947 Batch EC2 DescribeInstances calls
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1956 Remove unused 'IsExistInstance'
  pkg/cloud/cloud.go
  pkg/cloud/cloud_interface.go
  pkg/cloud/mock_cloud.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1959 Address CVE GO-2024-2611
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, lgtm, approved

#1954 Add helm-tester enabled flag
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, tide/merge-method-squash, lgtm, size/XS, approved, ok-to-test

#1957 Add helm wrapper to convert --reuse-values to --reset-then-reuse-values for CT testing
  hack/tools/helm-runner.sh
  hack/tools/install.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#1960 Return ErrInvalidArgument in cloud upon EC2 ModifyVolume
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller_modify_volume.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1962 Fix link in Volume Modification example docs
  examples/kubernetes/modify-volume/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1961 Add c6id and r6id adjusted limits to volume_limits.go
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#1968 Randomly generate tag names in e2e tests to prevent flakes due to collisions
  go.mod
  tests/e2e/requires_aws_api.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#1966 Add missing instances to instance store volumes table
  hack/generate-instance-store-table.sh
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#1969 Validate Karpenter Disruption taints as part of preStop node evaluation
  cmd/hooks/prestop.go
  cmd/hooks/prestop_test.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1971 Upgrade golangci-lint
  cmd/hooks/prestop_test.go
  hack/tools/install.sh
  pkg/cloud/cloud_test.go
  pkg/driver/controller_modify_volume_test.go
  pkg/driver/controller_test.go
  pkg/driver/node.go
  pkg/driver/node_linux_test.go
  pkg/driver/node_test.go
  pkg/mounter/safe_mounter_unix_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration/integration_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1975 Upgrade go/sidecar dependencies ahead of driver v1.29.0
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/tools/install.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#1977 Release aws-ebs-csi-driver v1.29.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1980 Bump helm chart version to v2.29.0
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1978 Fixup Helm test job
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
  charts/aws-ebs-csi-driver/values.yaml
  hack/prow-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#1979 Release v1.29.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#1976 Fix `ebs-csi-driver-test` CT pod timeout
  hack/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1984 Update Support Issue Template to Reflect Correct Slack Channel Name for AWS Provider
  .github/ISSUE_TEMPLATE/support-request.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1985 [master] Hardcode buildkit verison to 0.12.5
  hack/e2e/ecr.sh
  hack/prow.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1986 [release-1.29] Hardcode buildkit verison to 0.12.5
  hack/e2e/ecr.sh
  hack/prow.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1988 Release v1.29.1
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/NOTES.txt
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#1991 Update voluemessnapshotcontents/status RBAC
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
  deploy/kubernetes/base/clusterrole-snapshotter.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved
