Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-06, with the labels that each got.

#2055 Bump go to 1.22.4 to make govulncheck happy
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2053 Add tolerateAllTaints advice to Karpenter FAQ
  docs/faq.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2059 Use {{ .Release.Namespace }} in ClusterRoleBinding subject namespace
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2060 Add terminationGracePeriodSeconds as a helm parameter
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, tide/merge-method-squash, lgtm, size/XS, approved, ok-to-test

#2057 Increase default provisioner, resizer, snapshotter `retry-interval-max`
  charts/aws-ebs-csi-driver/templates/controller.yaml
  deploy/kubernetes/base/controller.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2061 Set RuntimeDefault as default seccompProfile in securityContext
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2065 Fix EC2MetadataInstanceInfo ENI calculation
  pkg/cloud/metadata/ec2.go
  pkg/cloud/metadata/metadata_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2069 Dependency Bump Release v1.32.0
  charts/aws-ebs-csi-driver/templates/clusterrole-provisioner.yaml
  charts/aws-ebs-csi-driver/values.yaml
  cloudbuild.yaml
  deploy/kubernetes/base/clusterrole-provisioner.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/tools/install.sh
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, lgtm, approved, size/XL

#2073 Release v1.32.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2074 Finalize Release 1.32
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2077 [release-1.32] Add topology label warning to changelog; Backout kops to 1.29
  CHANGELOG.md
  hack/e2e/config.sh
  hack/tools/install.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved
