Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2024-10, with the labels that each got.

#2159 feat: Added new policy to PodDisruptionBudget
  charts/aws-ebs-csi-driver/templates/poddisruptionbudget-controller.yaml
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2163 Update example policy for IAM change
  docs/example-iam-policy.json
  hack/e2e/kops/patch-cluster.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2167 docs: Fix typo in volume topology zone match label
  docs/parameters.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2168 Add EnableFSRs to example policy
  docs/example-iam-policy.json
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2169 Update FAQ to include section on Volume Attachment Capacity Issues
  docs/faq.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#2166 Add v1 Karpenter disrupted taint to pre-stop hook
  cmd/hooks/prestop.go
  cmd/hooks/prestop_test.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, lgtm, approved

#2174 Fix typos in options.go and cloud_test.go
  pkg/cloud/cloud_test.go
  pkg/driver/options.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2175 Bump GH actions (trivy, codeql, upload-artifact)
  .github/workflows/generate-code-coverage.yaml
  .github/workflows/trivy-containers.yaml
  .github/workflows/trivy.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2165 helm: add recommended autoscalar Tolerations to driver DaemonSet
  charts/aws-ebs-csi-driver/templates/_helpers.tpl
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
Labels: cncf-cla: yes, size/S, lgtm, approved

#2177 Automate image dependency upgrades & Migrate to kubekins-e2e-v2
  Makefile
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
  charts/aws-ebs-csi-driver/values.yaml
  docs/makefile.md
  hack/release-scripts/update-e2e-images
Labels: cncf-cla: yes, tide/merge-method-squash, lgtm, size/M, approved

#2181 Add m8g, c8g, x8g, g6e, and p5e attachment limits
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#2183 Only bail to AttachVolume if volume is detached
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#2184 Release EBS CSI Driver v1.36.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2185 Release EBS CSI Driver v1.36.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2179 Add Dependabot for Go module & GitHub Action dependencies
  .github/dependabot.yaml
  docs/updating-dependencies.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#2189 Update parameters.md to fix a typo in `allowedTopologies`
  docs/parameters.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2191 Add warning about upcoming IAM update
  CHANGELOG.md
  README.md
  charts/aws-ebs-csi-driver/templates/NOTES.txt
Labels: cncf-cla: yes, size/S, lgtm, approved

#2160 Add K8s 1.31 to CI by pinning kops commit instead of version
  hack/e2e/config.sh
  hack/e2e/kops/kops.sh
  hack/tools/install.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2193 Update example-iam-policy.json
  docs/example-iam-policy.json
  hack/e2e/kops/patch-cluster.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#2197 Stub nodeService to improve macos devloop
  pkg/mounter/mount_unsupported.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2203 Fix fetching test package version for kubetest in helm-tester
  charts/aws-ebs-csi-driver/templates/tests/helm-tester.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2196 Add middleware to log server errors
  pkg/cloud/cloud.go
  pkg/cloud/handlers.go
Labels: cncf-cla: yes, lgtm, size/M, approved
