Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-09, with the labels that each got.

#2654 Add containerPort spec for metrics endpoint
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/controller.yaml
Labels: cncf-cla: yes, kind/feature, lgtm, size/M, approved, release-note

#2672 Add FallbackToLogsOnError termination message policy to all containers
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/templates/controller.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, kind/feature, size/S, release-note-none, lgtm, approved

#2675 Relase Helm Chart v2.49.1
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, release-note-none, lgtm, size/XS, approved

#2677 Bumping Dependencies Ahead of v1.50.0 release
  charts/aws-ebs-csi-driver/values.yaml
  go.mod
  go.sum
  hack/tools/install.sh
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, release-note-none, size/L, lgtm, approved
