Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-05, with the labels that each got.

#2458 Allow customizing snapshot-controller image in E2E tests
  hack/e2e/config.sh
  hack/e2e/run.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2460 Add comment clarifying disabling IMDS on eksctl clusters is intentional
  hack/e2e/eksctl/cluster.yaml
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2462 Upgrade dependencies
  go.mod
  go.sum
  pkg/driver/driver_test.go
  pkg/driver/mock_k8s_client.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#2463 Add support for specifying volume initialization rate
  docs/parameters.md
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  tests/e2e/requires_aws_api.go
Labels: cncf-cla: yes, kind/feature, size/L, lgtm, approved

#2464 Release aws-ebs-csi-driver v1.43.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#2465 Release 1.43
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#2467 Remove Snow Device Support
  docs/parameters.md
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/metadata/ec2.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/metadata_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/mounter/mount_linux.go
  pkg/mounter/mount_linux_test.go
  pkg/util/util.go
Labels: cncf-cla: yes, kind/feature, size/L, lgtm, approved

#2471 Separate go.mod for E2E tests (don't import k/k in driver binary)
  go.mod
  go.sum
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/mounter/mock_mount.go
  pkg/mounter/mount.go
  pkg/mounter/mount_linux.go
  pkg/mounter/mount_unsupported.go
  pkg/mounter/mount_windows.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/sanity/fake_sanity_mounter.go
Labels: cncf-cla: yes, release-note-none, kind/cleanup, size/XXL, lgtm, approved

#2475 Update io2MaxIOPSPerGb from 500 to 1000
  docs/parameters.md
  pkg/cloud/cloud.go
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#2478 Add security Makefile target
  Makefile
  hack/tools/check-security.sh
  hack/tools/install.sh
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/M, approved

#2479 Fix windows example
  examples/kubernetes/windows/README.md
  examples/kubernetes/windows/manifests/windows.yaml
Labels: cncf-cla: yes, release-note-none, kind/documentation, lgtm, size/XS, approved

#2480 Update tests/e2e go.mod in Dependabot
  .github/dependabot.yaml
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/XS, approved

#2484 Remove broken client-go replace
  go.mod
  go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, size/S, release-note-none, kind/cleanup, lgtm, approved

#2489 Have dependabot add release-note-none label
  .github/dependabot.yaml
Labels: cncf-cla: yes, release-note-none, lgtm, needs-rebase, size/XS, approved

#2486 Include tests/e2e go.mod in make update/gomod
  Makefile
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/XS, approved

#2456 Add snapshot-volume-scale to scalability test suite
  hack/ebs-scale-test/README.md
  hack/ebs-scale-test/helpers/cluster-setup/manage-cluster.sh
  hack/ebs-scale-test/helpers/cluster-setup/scale-driver-values.yaml
  hack/ebs-scale-test/helpers/scale-test/collect-and-export-metrics.sh
  hack/ebs-scale-test/helpers/scale-test/snapshot-volume-scale-test/snapshot-volume-scale.sh
  hack/ebs-scale-test/helpers/scale-test/snapshot-volume-scale-test/snapshot-volume-scale.yaml
  hack/ebs-scale-test/scale-test
Labels: cncf-cla: yes, size/L, lgtm, approved

#2494 Bumping dependencies ahead of 1.44 + CI Fix
  Makefile
  charts/aws-ebs-csi-driver/values.yaml
  cloudbuild.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/tools/install.sh
  pkg/cloud/volume_limits.go
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, release-note-none, size/XXL, lgtm, approved

#2499 Foramt dependabot.yaml with yq for consistency
  .github/dependabot.yaml
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/M, approved

#2497 Release EBS CSI Driver v1.44.0 & Helm Chart v2.44.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/NOTES.txt
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, release-note-none, size/L, lgtm, approved, ok-to-test

#2503 Finalize Release 1.44
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/NOTES.txt
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, tide/merge-method-squash, release-note-none, size/L, lgtm, approved

#2492 Reliably remove driver startup taint
  charts/aws-ebs-csi-driver/templates/clusterrole-csi-node.yaml
  deploy/kubernetes/base/clusterrole-csi-node.yaml
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XL

#2487 Move govulncheck from GH Action to Prow via 'make security'
  .github/workflows/govulncheck.yaml
  hack/tools/check-security.sh
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/M, approved

#2500 Return `ResourceExhausted` gRPC error code in `ControllerPublishVolume` when `AttachmentLimitExceeded`
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/M, approved
