Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-07, with the labels that each got.

#2541 Add Karpenter ebs-scale-test cluster type
  hack/ebs-scale-test/README.md
  hack/ebs-scale-test/helpers/cluster-setup/manage-cluster.sh
  hack/ebs-scale-test/helpers/cluster-setup/nodes-karpenter.yaml
  hack/ebs-scale-test/helpers/cluster-setup/scale-cluster-config.yaml
  hack/ebs-scale-test/helpers/scale-test/snapshot-volume-scale-test/snapshot-volume-scale.sh
  hack/ebs-scale-test/scale-test
Labels: cncf-cla: yes, kind/documentation, size/L, lgtm, approved, release-note

#2550 Replace provenance script with `BUILDX_NO_DEFAULT_ATTESTATIONS` env var
  Makefile
  hack/provenance.sh
Labels: cncf-cla: yes, release-note-none, lgtm, size/M, approved

#2545 Return Resource Exhausted When Exceeding Quotas
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_modify_volume.go
  pkg/driver/controller_test.go
Labels: cncf-cla: yes, kind/feature, size/L, lgtm, approved, release-note

#2562 Group Dependabot PRs
  .github/dependabot.yaml
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/XS, approved

#2565 Update dependencies
  .golangci.yml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/tools/install.sh
  pkg/cloud/volume_limits.go
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, release-note-none, size/L, lgtm, approved

#2568 Add blockAttachUntilInitialized SC parameter
  charts/aws-ebs-csi-driver/templates/controller.yaml
  deploy/kubernetes/base/controller.yaml
  docs/example-iam-policy.json
  go.mod
  go.sum
  hack/e2e/kops/patch-cluster.yaml
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/ec2_interface.go
  pkg/cloud/interface.go
  pkg/cloud/mock_cloud.go
  pkg/cloud/mock_ec2.go
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/requires_aws_api.go
  tests/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
  tests/sanity/fake_sanity_cloud.go
Labels: cncf-cla: yes, kind/feature, lgtm, approved, release-note, size/XL

#2564 Removing In-Driver Validation Already Done by EC2
  docs/parameters.md
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_modify_volume_test.go
  pkg/driver/controller_test.go
  pkg/driver/validation.go
  pkg/driver/validation_test.go
Labels: cncf-cla: yes, kind/feature, size/L, lgtm, approved, release-note
