Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-02, with the labels that each got.

#2325 Fix command in dep bump document
  docs/updating-dependencies.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2321 fix(helm): Add global as part of the values schema to allow sub-charting
  charts/aws-ebs-csi-driver/values.schema.json
  charts/aws-ebs-csi-driver/values.yaml
Labels: kind/bug, cncf-cla: yes, tide/merge-method-squash, size/XXL, lgtm, approved, ok-to-test

#2323 Update CI to use 1.32 eks and kops clusters
  hack/e2e/config.sh
  hack/e2e/metrics/metrics.sh
  hack/tools/install.sh
Labels: cncf-cla: yes, size/S, kind/cleanup, lgtm, approved

#2330 Add expand-and-modify test type to ebs-scale-test
  hack/ebs-scale-test/README.md
  hack/ebs-scale-test/helpers/scale-test/collect-and-export-metrics.sh
  hack/ebs-scale-test/helpers/scale-test/expand-and-modify-test/expand-and-modify.sh
  hack/ebs-scale-test/helpers/scale-test/expand-and-modify-test/expand-and-modify.yaml
  hack/ebs-scale-test/helpers/scale-test/pre_test_validation.sh
  hack/ebs-scale-test/helpers/scale-test/scale-sts-test/scale-sts.sh
  hack/ebs-scale-test/scale-test
Labels: cncf-cla: yes, kind/documentation, size/L, lgtm, approved

#2334 Fix raw pointer log in `EnableFastSnapshotRestores`
  pkg/cloud/cloud.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#2335 Reconcile some differences between helm chart and values.schema.json
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/values.schema.json
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/node-windows.yaml
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#2339 Update volume modification doc with correct VolumeAttributesClass link to k8s doc
  docs/modify-volume.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-ok-to-test

#2329 Update modify-volume example to fix syntax typo
  examples/kubernetes/modify-volume/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2343 Upgrade dependencies ahead of EBS CSI Driver v1.40.0
  Dockerfile
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/tools/install.sh
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, ok-to-test

#2349 Merge Release 1.40 branch into master
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#2342 Skip IMDS call if AWS_EC2_METADATA_DISABLED=true
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/metadata_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved

#2351 Update changelog to include String Interpolation and enableWindows
  CHANGELOG.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
Labels: cncf-cla: yes, kind/documentation, lgtm, size/XS, approved

#2352 cherry-pick Update changelog to include String Interpolation and enableWindows
  CHANGELOG.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2356 Fix incorrect properties validation in Helm schema
  charts/aws-ebs-csi-driver/values.schema.json
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved

#2357 Prevent null deref when enableWindows and otelTracing enabled on node
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#2360 Release helm chart 2.40.1
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2341 Initialize metrics at 0 on startup
  cmd/main.go
  pkg/cloud/handlers.go
  pkg/metrics/constants.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, kind/feature, size/L, lgtm, approved, ok-to-test

#2367 cleanup: `make verify` should ignore copyright year
  hack/verify-update.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2355 feat: Add error `code` label to EBS CSI API request error metrics
  pkg/cloud/handlers.go
Labels: cncf-cla: yes, kind/feature, lgtm, size/XS, approved

#2366 Release helm chart 2.40.2
  CHANGELOG.md
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/NOTES.txt
  charts/aws-ebs-csi-driver/values.schema.json
Labels: cncf-cla: yes, size/S, lgtm, approved

#2353 Fix p4d.24xlarge reporting wrong volume limit
  hack/generate-gpu-count-table.sh
  hack/generate-instance-store-table.sh
  pkg/cloud/volume_limits.go
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved
