Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-04, with the labels that each got.

#2429 Add Elijah to Security Contacts
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2430 Change stub NVMECollector from windows to non-linux platforms
  pkg/metrics/nvme_unsupported.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2432 Set internalTrafficPolicy to local on node metric service
  charts/aws-ebs-csi-driver/templates/metrics.yaml
Labels: cncf-cla: yes, kind/feature, lgtm, size/XS, approved

#2431 Add `go fix` to `make update`
  Makefile
  pkg/metrics/nvme.go
  pkg/metrics/nvme_test.go
  pkg/mounter/mount_linux.go
  pkg/mounter/mount_linux_test.go
  pkg/mounter/mount_unsupported.go
  pkg/mounter/mount_windows.go
  pkg/mounter/mount_windows_proxyV1.go
  pkg/mounter/mount_windows_proxyV2.go
  pkg/util/util_test.go
  tests/sanity/sanity_test.go
Labels: cncf-cla: yes, size/S, kind/cleanup, lgtm, approved

#2443 Bumping Dependencies Ahead of 1.42.0 release
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/tools/install.sh
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, ok-to-test

#2444 Release EBS CSI Driver v1.42.0 & Helm Chart v2.42.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2446 Release 1.42
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#2438 Refresh dynamic instance metadata for NodeGetInfo calls
  pkg/cloud/metadata/ec2.go
  pkg/cloud/metadata/interface.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/metadata_test.go
  pkg/cloud/metadata/mock_metadata.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  tests/sanity/fake_sanity_metadata_service.go
Labels: cncf-cla: yes, kind/feature, size/L, lgtm, approved
