Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-10, with the labels that each got.

#2682 Refactor To Get Maximum IOPS for Capping Through Error Message
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  tests/e2e/requires_aws_api.go
Labels: cncf-cla: yes, kind/feature, lgtm, approved, release-note, size/XL

#2686 Release v1.50.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, release-note-none, lgtm, size/M, approved

#2680 Update docs to include updated Outpost information
  docs/outposts.md
  docs/parameters.md
Labels: cncf-cla: yes, release-note-none, kind/documentation, lgtm, size/M, approved

#2694 Release v1.49.1
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, release-note-none, lgtm, size/M, approved
