Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-08, with the labels that each got.

#2601 SageMaker HyperPod AttachDisk and DetachDisk integration
  charts/aws-ebs-csi-driver/templates/controller.yaml
  cmd/main.go
  deploy/kubernetes/base/controller.yaml
  go.mod
  go.sum
  hack/update-mockgen.sh
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/metadata/k8s.go
  pkg/cloud/metadata/metadata_test.go
  pkg/cloud/mock_sm.go
  pkg/cloud/sagemaker_interface.go
  tests/e2e/dynamic_provisioning.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/pre_provsioning.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XL, ok-to-test

#2608 Bump cloudbuild to machine type with 32GB of RAM
  cloudbuild.yaml
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/XS, approved

#2607 Bump moby/buildkit image to v0.23.2
  hack/cloudbuild.sh
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/XS, approved

#2594 Add relabelings stanza for ServiceMonitor
  charts/aws-ebs-csi-driver/templates/metrics.yaml
  charts/aws-ebs-csi-driver/values.schema.json
Labels: cncf-cla: yes, size/S, tide/merge-method-squash, lgtm, approved, release-note, ok-to-test

#2613 Add ability to use az-id for volume provisioning
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, kind/feature, size/L, lgtm, approved, release-note

#2620 Call sts:GetCallerIdentity Just in Time instead of blocking on startup
  cmd/main.go
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  tests/e2e/dynamic_provisioning.go
  tests/e2e/pre_provsioning.go
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved, release-note

#2629 Run Helm release action on release branches, not master
  .github/workflows/helm-chart-release.yaml
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/XS, approved

#2626 Release v1.48.0
  .github/workflows/helm-chart-release.yaml
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, release-note-none, size/L, lgtm, approved

#2459 Allow customizing AMI of eksctl Linux/Windows nodes
  hack/e2e/config.sh
  hack/e2e/create-cluster.sh
  hack/e2e/eksctl/cluster.yaml
  hack/e2e/eksctl/eksctl.sh
  hack/prow-e2e.sh
Labels: cncf-cla: yes, release-note-none, lgtm, size/M, approved

#2628 Ensure codebase uses DriverName constant instead of ebs.csi.aws.com
  pkg/cloud/cloud.go
  pkg/driver/constants.go
  pkg/driver/driver.go
  pkg/driver/identity.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/util/util.go
  tests/e2e/driver/ebs_csi_driver.go
  tests/e2e/testsuites/modify_volume_tester.go
  tests/e2e/testsuites/testsuites.go
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/M, approved

#2632 Autofix some golangci-lint errors in make update
  Makefile
  hack/verify-update.sh
Labels: cncf-cla: yes, size/S, release-note-none, lgtm, approved

#2627 Enable std-error-handling linter
  .golangci.yml
  pkg/cloud/cloud.go
  pkg/metrics/nvme.go
  pkg/mounter/mount_linux_test.go
  tests/sanity/sanity_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, release-note-none, lgtm, size/M, approved

#2641 Makefile: Add validation to prevent Windows clusters with kOps
  hack/e2e/create-cluster.sh
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/XS, approved

#2639 Adding Check to Fail Test For Unusual # of Restarts
  hack/e2e/run.sh
Labels: cncf-cla: yes, release-note-none, lgtm, size/XS, approved

#2636 Not Returning Infeasible If Tags Were Modified
  pkg/driver/controller_modify_volume.go
Labels: kind/bug, cncf-cla: yes, release-note-none, lgtm, size/XS, approved
