Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-06, with the labels that each got.

#2516 Fix dependency upgrades
  go.mod
  go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, release-note-none, kind/cleanup, size/L, lgtm, approved

#2504 improving extraVolumeTags validation to follow EC2 tagging convention
  charts/aws-ebs-csi-driver/values.schema.json
Labels: kind/bug, cncf-cla: yes, tide/merge-method-squash, lgtm, size/XS, approved, release-note, ok-to-test

#2519 Use correct name for nvme_collector_duration_seconds
  docs/metrics.md
Labels: cncf-cla: yes, size/S, release-note-none, kind/documentation, lgtm, approved, ok-to-test

#2518 Upgrade dependencies ahead of v1.45
  charts/aws-ebs-csi-driver/values.schema.json
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/ecr/kustomization.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/e2e/eksctl/cluster.yaml
  hack/release-scripts/image-digests-template.yaml
  hack/tools/install.sh
  tests/e2e/go.mod
  tests/e2e/go.sum
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved, release-note

#2517 Add `--metadata-sources` parameter to opt-out or choose fallback ordering of metadata sources
  charts/aws-ebs-csi-driver/templates/_node-windows.tpl
  charts/aws-ebs-csi-driver/templates/_node.tpl
  charts/aws-ebs-csi-driver/values.schema.json
  charts/aws-ebs-csi-driver/values.yaml
  cmd/main.go
  docs/install.md
  docs/options.md
  pkg/cloud/metadata/imds.go
  pkg/cloud/metadata/interface.go
  pkg/cloud/metadata/metadata.go
  pkg/cloud/metadata/metadata_test.go
  pkg/cloud/metadata/mock_metadata.go
  pkg/driver/options.go
  pkg/driver/options_test.go
Labels: cncf-cla: yes, kind/feature, size/L, lgtm, approved, release-note

#2528 Release aws-ebs-csi-driver v1.45.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
  hack/ebs-scale-test/helpers/cluster-setup/scale-cluster-config.yaml
Labels: cncf-cla: yes, release-note-none, size/L, lgtm, approved

#2530 Release 1.45
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
  hack/ebs-scale-test/helpers/cluster-setup/scale-cluster-config.yaml
Labels: cncf-cla: yes, release-note-none, size/L, lgtm, approved

#2532 Release helm chart v2.45.1
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, tide/merge-method-squash, release-note-none, kind/cleanup, lgtm, size/M, approved

#2533 Release helm chart v2.45.1
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
Labels: cncf-cla: yes, release-note-none, lgtm, size/M, approved

#2529 Migrate to golangci-lint v2
  .golangci.yml
  hack/tools/install.sh
  pkg/cloud/cloud.go
  pkg/driver/controller.go
  pkg/mounter/mount_linux.go
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/M, approved

#2535 Add mdzraf to OWNERS file
  OWNERS
Labels: cncf-cla: yes, release-note-none, lgtm, size/XS, approved

#2539 Remove completed TODO comment
  pkg/cloud/cloud.go
Labels: cncf-cla: yes, release-note-none, kind/cleanup, lgtm, size/XS, approved
