Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-01, with the labels that each got.

#2275 Update volume modification example 6 hour cooldown note
  docs/modify-volume.md
Labels: cncf-cla: yes, kind/documentation, lgtm, size/XS, approved

#2254 Add csi-sanity tests
  .golangci.yml
  Makefile
  go.mod
  go.sum
  pkg/cloud/metadata/mock_metadata.go
  pkg/cloud/mock_cloud.go
  pkg/cloud/mock_ec2.go
  pkg/driver/controller_modify_volume.go
  pkg/driver/mock_k8s_client.go
  pkg/driver/mock_k8s_corev1.go
  pkg/driver/mock_k8s_storagev1.go
  pkg/driver/mock_k8s_storagev1_csinode.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/mounter/mock_mount.go
  tests/sanity/fake_sanity_cloud.go
  tests/sanity/fake_sanity_metadata_service.go
  tests/sanity/fake_sanity_mounter.go
  tests/sanity/sanity_test.go
Labels: cncf-cla: yes, kind/feature, lgtm, approved, size/XL

#2279 Change make test to also run sanity tests
  Makefile
Labels: cncf-cla: yes, kind/feature, lgtm, size/XS, approved

#2280 Fix cloudbuild.sh target
  hack/cloudbuild.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2282 Bump dependencies and lock errdefs version to v0.1.0
  go.mod
  go.sum
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#2281 Refactor driver permissions docs and add Pod Identities
  docs/install.md
Labels: cncf-cla: yes, kind/documentation, lgtm, size/M, approved

#2287 Update example policy and documentation
  docs/example-iam-policy.json
  docs/install.md
  hack/e2e/kops/patch-cluster.yaml
Labels: cncf-cla: yes, kind/documentation, size/L, lgtm, approved

#2303 Fix wait for volume ready ~60s
  pkg/cloud/cloud.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2304 Upgrade dependencies ahead of EBS CSI Driver v1.39.0
  .golangci.yml
  charts/aws-ebs-csi-driver/templates/clusterrole-snapshotter.yaml
  charts/aws-ebs-csi-driver/values.yaml
  cloudbuild.yaml
  deploy/kubernetes/base/clusterrole-snapshotter.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/tools/install.sh
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, tide/merge-method-squash, size/L, lgtm, approved

#2308 Release EBS CSI Driver v1.39.0 & Helm Chart v2.39.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#2289 Fast-fail `make e2e/single-az` if cluster has nodes in multiple AZs
  hack/e2e/run.sh
Labels: cncf-cla: yes, size/S, kind/cleanup, lgtm, approved

#2311 Fix node.selinux configuration parameter & release Helm Chart v2.39.1
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/_node.tpl
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#2310 Add EBS-backed Ephemeral Volume example to documentation
  examples/kubernetes/README.md
  examples/kubernetes/ephemeral-volume/README.md
  examples/kubernetes/ephemeral-volume/manifests/pod.yaml
  examples/kubernetes/ephemeral-volume/manifests/storageclass.yaml
Labels: cncf-cla: yes, kind/documentation, size/L, lgtm, approved

#2313 Fix: modify-volume doc typo
  docs/modify-volume.md
Labels: cncf-cla: yes, size/S, kind/cleanup, lgtm, approved, ok-to-test

#2314 [Cherry-pick release-1.39]: Release Helm Chart v2.39.1
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/_node.tpl
Labels: cncf-cla: yes, size/S, lgtm, approved

#2286 Add values.schema.json
  charts/aws-ebs-csi-driver/values.schema.json
  charts/aws-ebs-csi-driver/values.yaml
Labels: cncf-cla: yes, kind/feature, size/XXL, lgtm, approved

#2316 Fix helm regression with a1CompatibilityDaemonSet & release chart v2.39.2
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2317 [Cherry-pick release-1.39] Fix helm regression with a1CompatibilityDaemonSet & Release chart v2.39.2
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/node.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#2322 Release chart v2.39.3
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.schema.json
  charts/aws-ebs-csi-driver/values.yaml
Labels: kind/bug, cncf-cla: yes, size/XXL, lgtm, approved

#2292 Create EBS CSI Driver scale-test tool
  hack/ebs-scale-test/README.md
  hack/ebs-scale-test/helpers/cluster-setup/manage-cluster.sh
  hack/ebs-scale-test/helpers/cluster-setup/scale-cluster-config.yaml
  hack/ebs-scale-test/helpers/cluster-setup/scale-driver-values.yaml
  hack/ebs-scale-test/helpers/scale-test/collect-and-export-metrics.sh
  hack/ebs-scale-test/helpers/scale-test/pre_test_validation.sh
  hack/ebs-scale-test/helpers/scale-test/scale-sts-test/scale-sts.sh
  hack/ebs-scale-test/helpers/scale-test/scale-sts-test/scale-sts.yaml
  hack/ebs-scale-test/scale-test
Labels: cncf-cla: yes, kind/documentation, lgtm, approved, size/XL
