Repository kubernetes-sigs/aws-ebs-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#2374 Skip adding license header to auto-generated mock files
  hack/generate-license-header.sh
  pkg/cloud/metadata/mock_metadata.go
  pkg/cloud/mock_cloud.go
  pkg/cloud/mock_ec2.go
  pkg/driver/mock_k8s_client.go
  pkg/driver/mock_k8s_corev1.go
  pkg/driver/mock_k8s_storagev1.go
  pkg/driver/mock_k8s_storagev1_csinode.go
  pkg/mounter/mock_mount.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#2376 Remove deprecated linters from ignore
  .golangci.yml
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2382 Cherry-pick release-1.40: Add error code as a label to the aws_ebs_csi_api_request_errors_total
  go.mod
  go.sum
  pkg/cloud/handlers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2381 cherry-pick release-1.39: Add error code as a label to the aws_ebs_csi_api_request_errors_total
  Dockerfile
  go.mod
  go.sum
  hack/tools/install.sh
  pkg/cloud/handlers.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2384 Update tags in cloudbuild.sh/Makefile to match promoted images
  Makefile
  hack/cloudbuild.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2372 Adding Logs On How We Calculate CSINode.allocatables in NodeGetInfo
  pkg/cloud/metadata/ec2.go
  pkg/driver/node.go
Labels: cncf-cla: yes, size/S, kind/cleanup, lgtm, approved, ok-to-test

#2389 Fix incorrect schema entry for controller.podDisruptionBudget.unhealthyPodEvictionPolicy value
  charts/aws-ebs-csi-driver/values.schema.json
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2393 Release helm v2.40.3
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/gcr/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved

#2390 Switching deprecatedMetrics Default Value to False
  pkg/driver/options.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved, ok-to-test

#2398 Upgrade dependencies ahead of EBS CSI Driver v1.41.0
  charts/aws-ebs-csi-driver/values.yaml
  go.mod
  go.sum
  hack/e2e/config.sh
  hack/tools/install.sh
  pkg/cloud/volume_limits.go
Labels: cncf-cla: yes, tide/merge-method-squash, kind/cleanup, size/L, lgtm, approved, ok-to-test

#2403 Release aws-ebs-csi-driver 1.41 & Helm Chart v2.41.0
  CHANGELOG.md
  Makefile
  README.md
  charts/aws-ebs-csi-driver/CHANGELOG.md
  charts/aws-ebs-csi-driver/Chart.yaml
  charts/aws-ebs-csi-driver/templates/NOTES.txt
  charts/aws-ebs-csi-driver/values.yaml
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node-windows.yaml
  deploy/kubernetes/base/node.yaml
  docs/install.md
Labels: cncf-cla: yes, size/L, lgtm, approved

#2385 Add make file target for testing images
  Makefile
  hack/e2e/test-images.sh
Labels: cncf-cla: yes, kind/feature, lgtm, size/M, approved

#2399 Enable useTesting linter
  .golangci.yml
  pkg/cloud/cloud_test.go
  pkg/driver/controller_test.go
  pkg/driver/node_test.go
  pkg/driver/request_coalescing_test.go
Labels: cncf-cla: yes, kind/cleanup, size/L, lgtm, approved

#2406 Remove all examples/references to Docker Hub
  Dockerfile
  charts/aws-ebs-csi-driver/values.yaml
  examples/kubernetes/block-volume/manifests/pod.yaml
  examples/kubernetes/dynamic-provisioning/manifests/pod.yaml
  examples/kubernetes/ephemeral-volume/manifests/pod.yaml
  examples/kubernetes/modify-volume/manifests/pod-with-volume.yaml
  examples/kubernetes/resizing/manifests/pod.yaml
  examples/kubernetes/snapshot/manifests/app/pod.yaml
  examples/kubernetes/snapshot/manifests/snapshot-import/app/pod.yaml
  examples/kubernetes/snapshot/manifests/snapshot-restore/pod.yaml
  examples/kubernetes/static-provisioning/manifests/pod.yaml
  examples/kubernetes/storageclass/manifests/pod.yaml
Labels: cncf-cla: yes, kind/documentation, lgtm, size/M, approved

#2409 Fix to only initialize controller metrics in controller
  cmd/main.go
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved, ok-to-test

#2411 Add binary-based kops installation, retain commit as override
  hack/tools/install.sh
Labels: cncf-cla: yes, size/S, kind/cleanup, lgtm, approved

#2412 Add e2e tests for fips and a1compat images
  Makefile
  hack/prow-e2e.sh
Labels: cncf-cla: yes, kind/feature, lgtm, size/M, approved

#2414 Ignore ECR login failure in make cluster/image
  hack/e2e/build-image.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/XS, approved

#2410 chore: fix typo
  pkg/driver/node.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2415 Add make cluster/helm
  CONTRIBUTING.md
  Makefile
  docs/makefile.md
  hack/e2e/util.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved

#2420 Update README.md feature list to prevent common misconception
  README.md
Labels: cncf-cla: yes, kind/documentation, lgtm, size/XS, approved

#2418 Adding more metric specific HELP texts for controller metrics
  docs/metrics.md
  pkg/cloud/handlers.go
  pkg/metrics/constants.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved, ok-to-test

#2424 Output junit report for `tests/e2e/...` E2E jobs
  hack/e2e/config.sh
  hack/e2e/run.sh
Labels: cncf-cla: yes, kind/feature, lgtm, size/XS, approved

#2427 Update SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S, kind/documentation, lgtm, approved

#2419 Fix a1compat makefile target and fix fips CI jobs
  Makefile
  hack/e2e/build-image.sh
  hack/e2e/config.sh
  hack/prow-e2e.sh
Labels: cncf-cla: yes, kind/cleanup, lgtm, size/M, approved
